import { OrganizationSetup } from './OrganizationSetup';
import { useEffect, useState } from 'react';
import { signOut,authenticatedFetch,isDemoSession } from './auth';
import {LayoutDashboard,Users,ShieldCheck,History,ArrowUpRight,Plus,LogOut,LockKeyhole,ChevronRight,FolderTree,Search} from 'lucide-react';
interface Assignment { permission:string; scope:'OWN'|'ORGANIZATION'; effect:'ALLOW'|'DENY'; validUntil?:string }
interface Role { id:string; name:string; permissions:Assignment[] }
interface Person { id:string; displayName:string; employeeCode:string; active:boolean; roleIds:string[]; overrides:Assignment[] }
interface Preset {key:string;name:string;description:string;permissions:Assignment[];pending:{permission:string;scope:string}[]}
interface State { presets:Preset[]; revision:number; storage?:string;currentPerson?:Person;authentication?:string; roles:Role[]; people:Person[]; catalogue:{code:string;label:string}[]; canManageUsers:boolean; audit:{actorId:string;action:string;targetId:string;at:string;revision:number;after?:{name?:string}}[] }
const emptyRole = ():Role => ({id:'',name:'',permissions:[]});
const emptyPerson = ():Person => ({id:'',displayName:'',employeeCode:'',active:true,roleIds:[],overrides:[]});
type View='overview'|'roles'|'people'|'audit'|'organization'|'assignments';
const currentView=():View=>{const view=new URLSearchParams(window.location.search).get('view');return view&&['overview','roles','people','audit','organization','assignments'].includes(view)?view as View:'overview';};
const actionLabel=(action:string)=>({ 'organization.person.assigned':'Assignment updated','organization.node.created':'Organization added','organization.node.updated':'Organization updated','person.created':'Person added','person.updated':'Person updated','role.created':'Role created','role.updated':'Role updated' }[action]??action.replaceAll('.',' ').replaceAll('_',' '));
function PermissionEditor({ label, value, onChange, catalogue }: {label:string;value:Assignment[];onChange:(value:Assignment[])=>void;catalogue:State['catalogue']}) {
  const [code,setCode]=useState('profile.view');
  const [scope,setScope]=useState<Assignment['scope']>('OWN');
  return <fieldset className="permission-editor"><legend>{label}</legend><div className="permission-add"><label>Permission<select value={code} onChange={event=>setCode(event.target.value)}>{catalogue.map(item=><option key={item.code} value={item.code}>{item.label}</option>)}</select></label><label>Add scope<select value={scope} onChange={event=>setScope(event.target.value as Assignment['scope'])}><option value="OWN">Own records</option><option value="ORGANIZATION">Entire workspace</option></select></label><button type="button" className="secondary-button" disabled={value.some(item=>item.permission===code&&item.scope===scope)} onClick={()=>onChange([...value,{permission:code,effect:'ALLOW',scope}])}>Add permission</button></div>
    {value.length===0 && <p>No permissions assigned. Access is denied by default.</p>}
    {value.map((item,index)=><div className="permission-row" key={index}><strong>{catalogue.find(entry=>entry.code===item.permission)?.label??item.permission}</strong><label>Effect<select value={item.effect} onChange={event=>onChange(value.map((entry,i)=>i===index?{...entry,effect:event.target.value as Assignment['effect']}:entry))}><option value="ALLOW">Allow</option><option value="DENY">Block</option></select></label><label>Scope<select value={item.scope} onChange={event=>onChange(value.map((entry,i)=>i===index?{...entry,scope:event.target.value as Assignment['scope']}:entry))}><option value="OWN">Own records</option><option value="ORGANIZATION">Entire workspace</option></select></label><label>Expires (optional)<input type="datetime-local" value={item.validUntil ? new Date(Date.parse(item.validUntil)-new Date(item.validUntil).getTimezoneOffset()*60000).toISOString().slice(0,16) : ''} onChange={event=>onChange(value.map((entry,i)=>i===index?{...entry,validUntil:event.target.value?new Date(event.target.value).toISOString():undefined}:entry))}/></label><button type="button" className="secondary-button" aria-label={`Remove ${item.permission} permission ${index+1}`} onClick={()=>onChange(value.filter((_,i)=>i!==index))}>Remove</button></div>)}
  </fieldset>;
}
export function AccessAdmin() {
  const [state,setState]=useState<State>(); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
  const [role,setRole]=useState<Role>(emptyRole); const [person,setPerson]=useState<Person>(emptyPerson);
  const [search,setSearch]=useState('');
  const [organization,setOrganization]=useState<{nodes:{id:string;kind:string;name:string;parentId:string|null;active:boolean}[];assignments:{personId:string;departmentId:string|null;teamId:string|null}[]}>();
  const [assignmentDraft,setAssignmentDraft]=useState<Record<string,string[]>>({});
  const [department,setDepartment]=useState('');
  useEffect(()=>{if(!state?.canManageUsers||isDemoSession())return;const controller=new AbortController();authenticatedFetch('/api/access/organization',{signal:controller.signal}).then(async response=>{if(response.ok)setOrganization(await response.json());}).catch(()=>{});return()=>controller.abort();},[state?.revision]);
  const [busy,setBusy]=useState(false); const [tab,setTab]=useState<View>(currentView);
  useEffect(()=>{const url=new URL(window.location.href);url.searchParams.set('view',tab);window.history.replaceState(null,'',url);},[tab]);
  const endpoint=isDemoSession()?'/api/dev-access':'/api/access';
  async function load() {
    const response=await authenticatedFetch(endpoint);
    if (!response.ok) throw new Error(response.status===403?'Your ID does not have permission to administer access.':response.status===401?'Sign in with an assigned administrator ID.':'Local access administration is unavailable.');
    const data:State=await response.json(); setState(data); return data;
  }
  useEffect(()=>{let active=true;const controller=new AbortController();authenticatedFetch(endpoint,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error(response.status===403?'Your ID does not have permission to administer access.':'Sign in with your assigned Microsoft administrator account.'); const data:State=await response.json(); if(active)setState(data);}).catch(err=>{if(active)setError(err.message);});return()=>{active=false;controller.abort();};},[endpoint]);
  async function save(kind:'role'|'person') {
    if(!state)return; setBusy(true);setError('');setNotice('');
    try {
      const value=kind==='role'?role:person;
      const response=await authenticatedFetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...value,id:value.id||undefined,kind,revision:state.revision})});
      if(!response.ok){const result=await response.json().catch(()=>undefined);throw new Error(result?.error?.message??'The change could not be saved.');}
      await load(); if(kind==='role')setRole(emptyRole());else setPerson(emptyPerson());setNotice('Saved. Current permissions apply immediately.');
    }catch(err){setError(err instanceof Error?err.message:'The change could not be saved.');}finally{setBusy(false);}
  }
  async function saveAssignments(){
    if(!state||busy)return;const pending=state.people.filter(item=>assignmentDraft[item.id]&&JSON.stringify([...item.roleIds].sort())!==JSON.stringify([...assignmentDraft[item.id]].sort()));
    setBusy(true);setError('');setNotice('');let saved=0;
    try {for(const item of pending){const response=await authenticatedFetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...item,roleIds:assignmentDraft[item.id],kind:'person',revision:state.revision+saved})});
      if(!response.ok){const body=await response.json().catch(()=>undefined);throw new Error(body?.error?.message??'Assignments could not be saved.');}saved++;setAssignmentDraft(current=>{const next={...current};delete next[item.id];return next;});}
      await load();setNotice('Saved '+saved+' people.');
    }catch(err){await load().catch(()=>{});setError((err instanceof Error?err.message:'Save failed.')+' '+saved+' people saved. Review remaining selections before saving again.');}finally{setBusy(false);}
  }
  const visibleAudit=state?.audit.filter(item=>(item.action+' '+actionLabel(item.action)+' '+(state.people.find(person=>person.id===item.actorId)?.displayName??'')+' '+(state.roles.find(role=>role.id===item.targetId)?.name??state.people.find(person=>person.id===item.targetId)?.displayName??item.after?.name??'')).toLowerCase().includes(search.toLowerCase()))??[];
  const name=state?.currentPerson?.displayName??'Workspace administrator';
  const sections=[{id:'overview',label:'Dashboard',icon:LayoutDashboard},{id:'organization',label:'Organization',icon:FolderTree},{id:'people',label:'People',icon:Users},{id:'roles',label:'Roles & permissions',icon:ShieldCheck},{id:'assignments',label:'Role assignments',icon:Users},{id:'audit',label:'Activity log',icon:History}] as const;
  return <div className="admin-shell"><a className="skip-link" href="#access-main">Skip to content</a><aside className="admin-sidebar"><a className="admin-brand" href="/access"><img src="/brand/sopra-steria.svg" alt="Sopra Steria"/></a><div className="admin-workspace"><span className="workspace-symbol"><ShieldCheck size={20}/></span><div><strong>Skill Management</strong><span>Administration</span></div></div><p className="nav-caption">WORKSPACE</p><nav aria-label="Administration sections">{sections.map(({id,label,icon:Icon})=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>{setTab(id);setSearch('');setNotice('');}}><Icon size={19}/>{label}{tab===id&&<ChevronRight size={15}/>}</button>)}</nav><div className="admin-account"><span className="account-avatar">{name.split(/\s+/).slice(0,2).map(part=>part[0]).join('')}</span><div><strong>{name}</strong><span>{state?.authentication==='microsoft'?'Microsoft account':'Administrator'}</span></div><button aria-label="Sign out" onClick={()=>{signOut().catch(()=>setError('Sign out could not finish.'));}}><LogOut size={18}/></button></div></aside>
    <div className="admin-content"><header className="admin-topbar"><span>Workspace <ChevronRight size={14}/><strong>{sections.find(section=>section.id===tab)?.label}</strong></span><span className="session-badge"><LockKeyhole size={14}/>{state?.authentication==='microsoft'?'Microsoft verified':isDemoSession()?'Development session':'Verifying session'}</span><button className="mobile-admin-signout secondary-button" aria-label="Sign out" onClick={()=>{signOut().catch(()=>setError("Sign out could not finish."));}}><LogOut size={16}/></button></header><main id="access-main" className="access-main"><div className="admin-page-heading"><div><h1>{tab==='overview'?'Dashboard':tab==='assignments'?'Role assignments':tab==='roles'?'Roles & permissions':tab==='people'?'People':tab==='organization'?'Organization':'Activity log'}</h1><p className="subtitle">{tab==='overview'?'Manage your workspace.':tab==='assignments'?'Assign roles to people.':tab==='roles'?'Set what each role can do.':tab==='people'?'Manage access for each person.':tab==='organization'?'Departments and reporting lines.':'Review workspace changes.'}</p></div>{state&&<span className="admin-environment"><span/>Development workspace</span>}</div>
      {error&&<div className="access-message" role="alert">{error}<button className="secondary-button" onClick={()=>{setError('');load().catch(err=>setError(err.message));}}>Reload current configuration</button></div>}{notice&&<p className="access-message" role="status">{notice}</p>}
      {!state&&!error&&<div className="admin-loading" role="status">Loading your administration workspace…</div>}
      {state&&<>
      {tab==='overview'&&<>
        <div className="dashboard-actions">{state.canManageUsers&&<button className="admin-primary" onClick={()=>{setTab('people');setPerson(emptyPerson());}}><Plus size={17}/>Add person</button>}<button className="secondary-button" onClick={()=>{setTab('roles');setRole(emptyRole());}}>Create role</button><button className="secondary-button" onClick={()=>setTab('organization')}>View organization</button></div>
        <div className="admin-metrics">{[{label:'People',value:state.people.length,detail:state.people.filter(person=>person.active).length+' active',icon:Users,target:'people'},{label:'Roles',value:state.roles.length,detail:'Manage permissions',icon:ShieldCheck,target:'roles'},{label:'Departments',value:organization?organization.nodes.filter(node=>node.kind==='DEPARTMENT'&&node.active).length:'…',detail:'View organization',icon:FolderTree,target:'organization'}].map(({label,value,detail,icon:Icon,target})=><button className="metric-card" key={label} onClick={()=>setTab(target as typeof tab)}><span className="metric-label">{label}<Icon size={19} aria-hidden="true"/></span><strong>{value}</strong><span className="metric-detail">{detail}<ArrowUpRight size={16} aria-hidden="true"/></span></button>)}</div>
        <section className="profile-panel overview-activity"><div className="panel-title"><h2>Recent activity</h2><button className="admin-text-button" onClick={()=>setTab('audit')}>View all <ArrowUpRight size={16}/></button></div>{state.audit.length?[...state.audit].reverse().slice(0,5).map(item=><div className="activity-item" key={item.revision}><span className="activity-icon" aria-hidden="true">{item.action.startsWith('role')?<ShieldCheck size={18}/>:<Users size={18}/>}</span><div><strong>{actionLabel(item.action)}</strong><p>{state.people.find(person=>person.id===item.actorId)?.displayName??'Administrator'} · {state.roles.find(role=>role.id===item.targetId)?.name??state.people.find(person=>person.id===item.targetId)?.displayName??item.after?.name??'Workspace'}</p></div><time dateTime={item.at}>{new Date(item.at).toLocaleString()}</time></div>):<p>No recent changes.</p>}</section>
      </>}
      {tab==='organization'&&<OrganizationSetup onChanged={()=>{load().catch(err=>setError(err.message));}} onEditPerson={id=>{const selected=state.people.find(item=>item.id===id);if(selected){setPerson(structuredClone(selected));setTab('people');}}} onAssignDepartment={id=>{setDepartment(id);setTab('assignments');}} roleNames={Object.fromEntries(state.people.map(item=>[item.id,state.roles.filter(role=>item.roleIds.includes(role.id)).map(role=>role.name)]))}/>}
      {tab==='roles'&&<><details className="profile-panel role-presets"><summary>Start from a permission set</summary><div className="preset-buttons">{state.presets.map(preset=><button type="button" className="secondary-button" key={preset.key} onClick={()=>{setRole(structuredClone(state.roles.find(item=>item.name===preset.name)??{id:'',name:preset.name,permissions:preset.permissions}));}}>{preset.name}</button>)}</div>{state.presets.filter(preset=>preset.name===role.name).map(preset=><div key={preset.key} className="preset-detail"><p>{preset.description}</p>{preset.pending.length>0&&<p>Pending organization setup: {preset.pending.map(item=>(state.catalogue.find(entry=>entry.code===item.permission)?.label??item.permission)+' ('+item.scope.toLowerCase().replaceAll('_',' ')+')').join(', ')}. These proposals do not grant access yet.</p>}</div>)}</details><div className="access-columns"><section className="profile-panel"><h2>Roles</h2><label className="list-search"><Search size={16} aria-hidden="true"/><input aria-label="Search roles" placeholder="Search roles…" value={search} onChange={event=>setSearch(event.target.value)}/></label><button className="secondary-button" onClick={()=>setRole(emptyRole())}>New role</button><ul className="access-list">{!state.roles.some(item=>item.name.toLowerCase().includes(search.toLowerCase()))&&<li className="list-empty">No matching roles.</li>}{state.roles.filter(item=>item.name.toLowerCase().includes(search.toLowerCase())).map(item=><li key={item.id}><button aria-pressed={role.id===item.id} onClick={()=>setRole(structuredClone(item))}><strong>{item.name}</strong><span>{item.permissions.length} permission assignments</span></button></li>)}</ul></section><form className="profile-panel access-form" onSubmit={event=>{event.preventDefault();void save('role');}}><h2>{role.id?'Edit role':'Create role'}</h2><label>Role name<input required maxLength={100} value={role.name} onChange={event=>setRole({...role,name:event.target.value})}/></label><PermissionEditor label="Role permissions" value={role.permissions} onChange={permissions=>setRole({...role,permissions})} catalogue={state.catalogue}/><button className="microsoft-button" disabled={busy}>{busy?'Saving…':'Save role'}</button></form></div></>}
      {tab==='people'&&<div className="access-columns"><section className="profile-panel"><h2>People</h2><label className="list-search"><Search size={16} aria-hidden="true"/><input aria-label="Search people" placeholder="Name or employee ID…" value={search} onChange={event=>setSearch(event.target.value)}/></label>{state.canManageUsers&&<button className="secondary-button" onClick={()=>setPerson(emptyPerson())}>New person</button>}<ul className="access-list">{!state.people.some(item=>(item.displayName+' '+item.employeeCode).toLowerCase().includes(search.toLowerCase()))&&<li className="list-empty">No matching people.</li>}{state.people.filter(item=>(item.displayName+' '+item.employeeCode).toLowerCase().includes(search.toLowerCase())).map(item=><li key={item.id}><button aria-pressed={person.id===item.id} onClick={()=>setPerson(structuredClone(item))}><strong>{item.displayName}</strong><span>{item.employeeCode} · {item.active?'Active':'Suspended'}</span></button></li>)}</ul></section>{state.canManageUsers?<form className="profile-panel access-form" onSubmit={event=>{event.preventDefault();void save('person');}}><h2>{person.id?'Edit person':'Create person'}</h2><label>Display name<input required maxLength={100} value={person.displayName} onChange={event=>setPerson({...person,displayName:event.target.value})}/></label><label>Person ID<input required maxLength={40} value={person.employeeCode} onChange={event=>setPerson({...person,employeeCode:event.target.value})}/></label><label className="access-check"><input type="checkbox" checked={person.active} onChange={event=>setPerson({...person,active:event.target.checked})}/>Active account</label><fieldset><legend>Assigned roles</legend><div className="audit-scroll"><table className="role-checkbox-table"><thead><tr><th>Assign</th><th>Role</th><th>Permissions</th></tr></thead><tbody>{state.roles.map(item=><tr key={item.id}><td><input type="checkbox" aria-label={'Assign '+item.name+' to '+(person.displayName||'new person')} checked={person.roleIds.includes(item.id)} onChange={event=>setPerson({...person,roleIds:event.target.checked?[...person.roleIds,item.id]:person.roleIds.filter(id=>id!==item.id)})}/></td><td>{item.name}</td><td>{item.permissions.length}</td></tr>)}</tbody></table></div></fieldset><details className="advanced-access"><summary>Individual permissions</summary><PermissionEditor label="Individual permission overrides" value={person.overrides} onChange={overrides=>setPerson({...person,overrides})} catalogue={state.catalogue}/><p className="access-help">Removing an individual ALLOW leaves inherited role permissions. Use DENY to block an inherited permission. An applicable DENY wins.</p></details><button className="microsoft-button" disabled={busy}>{busy?'Saving…':'Save person'}</button></form>:<section className="profile-panel">Your ID cannot manage people.</section>}</div>}
      {tab==='assignments'&&<section className="profile-panel"><div className="panel-title"><label className="list-search"><Search size={16}/><input aria-label="Search role assignments" placeholder="Search people…" value={search} onChange={event=>setSearch(event.target.value)}/></label><label className="department-filter">Department<select value={department} onChange={event=>setDepartment(event.target.value)}><option value="">All people</option>{organization?.nodes.filter(node=>node.kind==='DEPARTMENT'&&node.active).map(node=><option value={node.id} key={node.id}>{node.name}</option>)}</select></label><button className="admin-primary" disabled={busy||!Object.keys(assignmentDraft).length||!state.canManageUsers} onClick={()=>void saveAssignments()}>{busy?'Saving…':'Save assignments'}</button></div><div className="audit-scroll assignment-matrix"><table><thead><tr><th>Person</th>{state.roles.map(role=><th key={role.id}>{role.name}</th>)}</tr></thead><tbody>{state.people.filter(item=>(item.displayName+' '+item.employeeCode).toLowerCase().includes(search.toLowerCase())&&(!department||organization?.assignments.some(edge=>edge.personId===item.id&&(edge.departmentId===department||organization.nodes.some(node=>node.id===edge.teamId&&node.parentId===department))))).map(item=><tr key={item.id}><th scope="row"><strong>{item.displayName}</strong><small>{item.employeeCode}{!item.active?' · Suspended':''}</small></th>{state.roles.map(role=><td key={role.id}><input type="checkbox" disabled={busy||!state.canManageUsers} aria-label={'Assign '+role.name+' to '+item.displayName} checked={(assignmentDraft[item.id]??item.roleIds).includes(role.id)} onChange={event=>setAssignmentDraft(current=>{const ids=current[item.id]??item.roleIds;return {...current,[item.id]:event.target.checked?[...ids,role.id]:ids.filter(id=>id!==role.id)};})}/></td>)}</tr>)}</tbody></table></div></section>}
      {tab==='audit'&&<section className="profile-panel"><div className="panel-title"><h2>Activity log</h2><label className="list-search"><Search size={16} aria-hidden="true"/><input aria-label="Search activity" placeholder="Search activity…" value={search} onChange={event=>setSearch(event.target.value)}/></label></div>{!state.audit.length?<p>No visible changes recorded.</p>:<div className="audit-scroll"><table><thead><tr><th>Time</th><th>Action</th><th>Actor</th><th>Target</th></tr></thead><tbody>{!visibleAudit.length&&<tr><td colSpan={4}>No matching changes.</td></tr>}{[...visibleAudit].reverse().map(item=><tr key={item.revision}><td>{new Date(item.at).toLocaleString()}</td><td className="audit-action">{actionLabel(item.action)}</td><td>{state.people.find(person=>person.id===item.actorId)?.displayName??item.actorId}</td><td>{state.roles.find(role=>role.id===item.targetId)?.name??state.people.find(person=>person.id===item.targetId)?.displayName??item.after?.name??item.targetId}</td></tr>)}</tbody></table></div>}</section>}
      </>}
    </main></div></div>;
}
