import { OrganizationSetup } from './OrganizationSetup';
import { SkillCatalogue } from './SkillCatalogue';
import { FormDialog } from './FormDialog';
import { NavigationDrawer } from './NavigationDrawer';
import { Sidebar } from './Sidebar';
import { NavbarAccount } from './NavbarAccount';
import { RoleAssignments } from './RoleAssignments';
import { PermissionEditor } from './PermissionEditor';
import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router';
import { authenticatedFetch,isDemoSession } from './auth';
import {LayoutDashboard,Users,ShieldCheck,History,ArrowUpRight,Plus,BookOpen,ChevronRight,FolderTree,Search,Menu} from 'lucide-react';
interface Assignment { permission:string; scope:'OWN'|'ORGANIZATION'; effect:'ALLOW'|'DENY'; validUntil?:string }
interface Role { id:string; name:string; permissions:Assignment[] }
interface Person { id:string; displayName:string; employeeCode:string; active:boolean; roleIds:string[]; overrides:Assignment[] }
interface Preset {key:string;name:string;description:string;permissions:Assignment[];pending:{permission:string;scope:string}[]}
interface State { presets:Preset[]; revision:number; storage?:string;currentPerson?:Person;authentication?:string; roles:Role[]; people:Person[]; catalogue:{code:string;label:string}[]; canManageUsers:boolean; canViewSkills?:boolean; canViewAudit?:boolean; audit:{actorId:string;action:string;targetId:string;at:string;revision:number;after?:{name?:string}}[] }
const emptyRole = ():Role => ({id:'',name:'',permissions:[]});
const emptyPerson = ():Person => ({id:'',displayName:'',employeeCode:'',active:true,roleIds:[],overrides:[]});
type View='overview'|'roles'|'people'|'audit'|'organization'|'assignments'|'skills';
const currentView=(params:URLSearchParams):View=>{const view=params.get('view');return view&&['overview','roles','people','audit','organization','assignments','skills'].includes(view)?view as View:'overview';};
const actionLabel=(action:string)=>({ 'organization.person.assigned':'Assignment updated','organization.node.created':'Organization added','organization.node.updated':'Organization updated','person.created':'Person added','person.updated':'Person updated','claim.draft.created':'Skill draft added','claim.draft.updated':'Skill draft updated','skill.created':'Skill created','skill.updated':'Skill updated','role.created':'Role created','role.updated':'Role updated' }[action]??action.replaceAll('.',' ').replaceAll('_',' '));
export function AccessAdmin() {
  const [state,setState]=useState<State>(); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
  const [role,setRole]=useState<Role>(emptyRole); const [person,setPerson]=useState<Person>(emptyPerson);
  const [editor,setEditor]=useState<'role'|'person'>(),[editorPage,setEditorPage]=useState(0),[editorRevision,setEditorRevision]=useState(0),[rolePage,setRolePage]=useState(0);
  const [search,setSearch]=useState('');
  const [navigationOpen,setNavigationOpen]=useState(false);
  const [pageActions,setPageActions]=useState<HTMLDivElement|null>(null);
  const [organization,setOrganization]=useState<{nodes:{id:string;kind:string;name:string;parentId:string|null;active:boolean}[];assignments:{personId:string;departmentId:string|null;teamId:string|null}[]}>();
  const [assignmentDraft,setAssignmentDraft]=useState<Record<string,string[]>>({});
  const [department,setDepartment]=useState('');
  useEffect(()=>{if(!state?.canManageUsers||isDemoSession())return;const controller=new AbortController();authenticatedFetch('/api/access/organization',{signal:controller.signal}).then(async response=>{if(response.ok)setOrganization(await response.json());}).catch(()=>{});return()=>controller.abort();},[state?.revision]);
  const [busy,setBusy]=useState(false); const [params,setParams]=useSearchParams(); const tab=currentView(params);
  function setTab(view:View){setParams(current=>{const next=new URLSearchParams(current);next.set('view',view);return next;});}
  useEffect(()=>{window.scrollTo({top:0});},[tab]);
  const endpoint=isDemoSession()?'/api/dev-access':'/api/access';
  function createRecord(kind:'person'|'role') {
    setTab(kind==='person'?'people':'roles');setSearch('');setNotice('');setError('');setEditor(kind);setEditorPage(0);setRolePage(0);setEditorRevision(state?.revision??0);
    if(kind==='person')setPerson(emptyPerson());else setRole(emptyRole());
    requestAnimationFrame(()=>document.querySelector<HTMLInputElement>(`#${kind}-editor input`)?.focus());
  }
  async function load() {
    const response=await authenticatedFetch(endpoint);
    if (!response.ok) throw new Error(response.status===403?'Your ID does not have permission to administer access.':response.status===401?'Sign in with an assigned administrator ID.':'Local access administration is unavailable.');
    const data:State=await response.json(); setState(data); return data;
  }
  useEffect(()=>{let active=true;const controller=new AbortController();authenticatedFetch(endpoint,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error(response.status===403?'Your ID does not have permission to administer access.':'Sign in with your assigned Microsoft administrator account.'); const data:State=await response.json(); if(active)setState(data);}).catch(err=>{if(active)setError(err.message);});return()=>{active=false;controller.abort();};},[endpoint]);
  async function save(kind:'role'|'person') {
    if(!state)return; setBusy(true);setError('');setNotice('');
    try {
      const value=kind==='role'?role:person;
      const response=await authenticatedFetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...value,id:value.id||undefined,kind,revision:editorRevision})});
      if(!response.ok){const result=await response.json().catch(()=>undefined);throw new Error(result?.error?.message??'The change could not be saved.');}
      await load();setEditor(undefined); if(kind==='role')setRole(emptyRole());else setPerson(emptyPerson());setNotice('Saved. Current permissions apply immediately.');
    }catch(err){setError(err instanceof Error?err.message:'The change could not be saved.');}finally{setBusy(false);}
  }
  async function saveAssignments(){
    if(!state||busy)return;const pending=state.people.filter(item=>assignmentDraft[item.id]&&JSON.stringify([...item.roleIds].sort())!==JSON.stringify([...assignmentDraft[item.id]].sort()));
    setBusy(true);setError('');setNotice('');let saved=0;
    try {for(const item of pending){const response=await authenticatedFetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...item,roleIds:assignmentDraft[item.id],kind:'person',revision:state.revision+saved})});
      if(!response.ok){const body=await response.json().catch(()=>undefined);throw new Error(body?.error?.message??'Assignments could not be saved.');}saved++;setAssignmentDraft(current=>{const next={...current};delete next[item.id];return next;});}
      await load();setNotice('Saved '+saved+' people.');
    }catch(err){await load().catch(()=>{});setError((err instanceof Error?err.message:'Save failed.')+' '+saved+' people saved. Review remaining selections before saving again.');}finally{setBusy(false);}
  }
  const visibleAudit=state?.audit.filter(item=>(item.action+' '+actionLabel(item.action)+' '+(state.people.find(person=>person.id===item.actorId)?.displayName??'')+' '+(state.roles.find(role=>role.id===item.targetId)?.name??state.people.find(person=>person.id===item.targetId)?.displayName??item.after?.name??'')).toLowerCase().includes(search.toLowerCase()))??[];
  const name=state?.currentPerson?.displayName??'Workspace administrator';
  const greetingName=state?.currentPerson?(name.trim().split(/\s+/)[0]||'there'):'there';
  const sections=[{id:'overview',label:'Dashboard',icon:LayoutDashboard},{id:'organization',label:'Organization',icon:FolderTree},{id:'skills',label:'Skill catalogue',icon:BookOpen},{id:'people',label:'People',icon:Users},{id:'roles',label:'Roles & permissions',icon:ShieldCheck},{id:'assignments',label:'Role assignments',icon:Users},{id:'audit',label:'Activity log',icon:History}] as const;
  const sidebarContent=(close:()=>void=()=>{})=><><Link className="admin-brand" to="/access"><img src="/brand/sopra-steria.svg" alt="Sopra Steria"/></Link><p className="nav-caption">WORKSPACE</p><nav aria-label="Administration sections">{sections.filter(section=>section.id==='overview'||section.id==='roles'||(section.id==='skills'?state?.canViewSkills:section.id==='audit'?state?.canViewAudit:state?.canManageUsers)).map(({id,label,icon:Icon})=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>{setTab(id);setEditor(undefined);setSearch('');setNotice('');close();}}><Icon size={19}/>{label}{tab===id&&<ChevronRight size={15}/>}</button>)}</nav></>;
  return <div className="admin-shell"><a className="skip-link" href="#access-main">Skip to content</a><Sidebar className="desktop-sidebar">{sidebarContent()}</Sidebar>{navigationOpen&&<NavigationDrawer onClose={()=>setNavigationOpen(false)}>{close=><Sidebar>{sidebarContent(close)}</Sidebar>}</NavigationDrawer>}
    <div className="admin-content"><header className="admin-topbar"><button className="navigation-toggle secondary-button" aria-label="Open navigation" aria-expanded={navigationOpen} aria-controls="workspace-navigation" onClick={()=>setNavigationOpen(true)}><Menu size={20}/></button><div className="page-location navbar-context"><div className="navbar-greeting"><span className="greeting-hello">Hello,</span><strong className="greeting-name" title={name}>{greetingName}</strong></div><h1>{sections.find(section=>section.id===tab)?.label}</h1></div><div className="page-actions" role="group" aria-label="Page actions" ref={setPageActions}>
      {state&&tab==='overview'&&<>{state.canManageUsers&&<button className="admin-primary" onClick={()=>createRecord('person')}><Plus size={17}/>Add person</button>}<button className="secondary-button" onClick={()=>createRecord('role')}>Create role</button></>}
      {state&&tab==='people'&&state.canManageUsers&&<><button className="secondary-button" disabled={busy} onClick={()=>createRecord('person')}><Plus size={16}/>New person</button></>}
      {state&&tab==='roles'&&<><button className="secondary-button" disabled={busy} onClick={()=>createRecord('role')}><Plus size={16}/>New role</button></>}
      {state&&tab==='audit'&&<label className="list-search"><Search size={16} aria-hidden="true"/><input aria-label="Search activity" placeholder="Search activity…" value={search} onChange={event=>setSearch(event.target.value)}/></label>}
      </div><NavbarAccount name={name} identity={state?.authentication==='microsoft'?'Microsoft account':'Development session'} workspaceLink={{href:'/workspace',label:'Personal workspace'}}/></header><main id="access-main" className="access-main">
      {error&&<div className="access-message" role="alert">{error}<button className="secondary-button" onClick={()=>{setError('');load().catch(err=>setError(err.message));}}>Reload current configuration</button></div>}{notice&&<p className="access-message" role="status">{notice}</p>}
      {!state&&!error&&<div className="admin-loading" role="status">Loading your administration workspace…</div>}
      {state&&<>
      {tab==='overview'&&<>

        <div className="admin-metrics">{[{label:'People',value:state.people.length,detail:state.people.filter(person=>person.active).length+' active',icon:Users,target:'people'},{label:'Roles',value:state.roles.length,detail:'Manage permissions',icon:ShieldCheck,target:'roles'},{label:'Departments',value:organization?organization.nodes.filter(node=>node.kind==='DEPARTMENT'&&node.active).length:'…',detail:'View organization',icon:FolderTree,target:'organization'}].map(({label,value,detail,icon:Icon,target})=><button className="metric-card" key={label} onClick={()=>setTab(target as typeof tab)}><span className="metric-label">{label}<Icon size={19} aria-hidden="true"/></span><strong>{value}</strong><span className="metric-detail">{detail}<ArrowUpRight size={16} aria-hidden="true"/></span></button>)}</div>
        <section className="profile-panel overview-activity"><div className="panel-title"><h2>Recent activity</h2><button className="admin-text-button" onClick={()=>setTab('audit')}>View all <ArrowUpRight size={16}/></button></div>{state.audit.length?[...state.audit].reverse().slice(0,5).map(item=><div className="activity-item" key={item.revision}><span className="activity-icon" aria-hidden="true">{item.action.startsWith('role')?<ShieldCheck size={18}/>:<Users size={18}/>}</span><div><strong>{actionLabel(item.action)}</strong><p>{state.people.find(person=>person.id===item.actorId)?.displayName??'Administrator'} · {state.roles.find(role=>role.id===item.targetId)?.name??state.people.find(person=>person.id===item.targetId)?.displayName??item.after?.name??'Workspace'}</p></div><time dateTime={item.at}>{new Date(item.at).toLocaleString()}</time></div>):<p>No recent changes.</p>}</section>
      </>}

      {tab==='skills'&&<SkillCatalogue actionsContainer={pageActions} onChanged={()=>{load().catch(err=>setError(err.message));}}/>}
      {tab==='organization'&&<OrganizationSetup actionsContainer={pageActions} onChanged={()=>{load().catch(err=>setError(err.message));}} onEditPerson={id=>{const selected=state.people.find(item=>item.id===id);if(selected){setPerson(structuredClone(selected));setTab('people');setEditor('person');setEditorPage(1);setRolePage(0);setEditorRevision(state.revision);setError('');}}} onAssignDepartment={id=>{setDepartment(id);setTab('assignments');}} roleNames={Object.fromEntries(state.people.map(item=>[item.id,state.roles.filter(role=>item.roleIds.includes(role.id)).map(role=>role.name)]))}/>}
      {tab==='roles'&&<><details className="profile-panel role-presets"><summary>Start from a permission set</summary><div className="preset-buttons">{state.presets.map(preset=><button type="button" className="secondary-button" key={preset.key} onClick={()=>{setRole(structuredClone(state.roles.find(item=>item.name===preset.name)??{id:'',name:preset.name,permissions:preset.permissions}));setEditor('role');setEditorPage(0);setEditorRevision(state.revision);setError('');}}>{preset.name}</button>)}</div>{state.presets.filter(preset=>preset.name===role.name).map(preset=><div key={preset.key} className="preset-detail"><p>{preset.description}</p>{preset.pending.length>0&&<p>Pending organization setup: {preset.pending.map(item=>(state.catalogue.find(entry=>entry.code===item.permission)?.label??item.permission)+' ('+item.scope.toLowerCase().replaceAll('_',' ')+')').join(', ')}. These proposals do not grant access yet.</p>}</div>)}</details><div className="access-columns"><section className="profile-panel"><h2>Roles</h2><label className="list-search"><Search size={16} aria-hidden="true"/><input aria-label="Search roles" placeholder="Search roles…" value={search} onChange={event=>setSearch(event.target.value)}/></label><ul className="access-list">{!state.roles.some(item=>item.name.toLowerCase().includes(search.toLowerCase()))&&<li className="list-empty">No matching roles.</li>}{state.roles.filter(item=>item.name.toLowerCase().includes(search.toLowerCase())).map(item=><li key={item.id}><button aria-pressed={role.id===item.id} onClick={()=>{setRole(structuredClone(item));setEditor('role');setEditorPage(0);setEditorRevision(state.revision);setError('');}}><strong>{item.name}</strong><span>{item.permissions.length} permission assignments</span></button></li>)}</ul></section></div></>}
      {tab==='people'&&<div className="access-columns"><section className="profile-panel"><h2>People</h2><label className="list-search"><Search size={16} aria-hidden="true"/><input aria-label="Search people" placeholder="Name or employee ID…" value={search} onChange={event=>setSearch(event.target.value)}/></label><ul className="access-list">{!state.people.some(item=>(item.displayName+' '+item.employeeCode).toLowerCase().includes(search.toLowerCase()))&&<li className="list-empty">No matching people.</li>}{state.people.filter(item=>(item.displayName+' '+item.employeeCode).toLowerCase().includes(search.toLowerCase())).map(item=><li key={item.id}><button aria-pressed={person.id===item.id} onClick={()=>{setPerson(structuredClone(item));setEditor('person');setEditorPage(0);setRolePage(0);setEditorRevision(state.revision);setError('');}}><strong>{item.displayName}</strong><span>{item.employeeCode} · {item.active?'Active':'Suspended'}</span></button></li>)}</ul></section></div>}
      {editor==='role'&&<FormDialog title={role.id?'Edit role':'Create role'} onClose={()=>setEditor(undefined)} busy={busy} formId="role-editor" onSubmit={()=>void save('role')} page={editorPage} onPageChange={setEditorPage} message={error&&<p role="alert">{error}</p>} footer={<><button type="button" className="secondary-button" disabled={busy} onClick={()=>setEditor(undefined)}>Cancel</button><button className="microsoft-button" form="role-editor" type="submit" disabled={busy}>{busy?'Saving…':'Save role'}</button></>} pages={[
        {label:'Details',content:<label>Role name<input required maxLength={100} value={role.name} onChange={event=>setRole({...role,name:event.target.value})}/></label>},
        {label:'Permissions',content:<PermissionEditor label="Role permissions" value={role.permissions} onChange={permissions=>setRole({...role,permissions})} catalogue={state.catalogue}/>}
      ]}/>}
      {editor==='person'&&state.canManageUsers&&<FormDialog title={person.id?'Edit person':'Create person'} onClose={()=>setEditor(undefined)} busy={busy} formId="person-editor" onSubmit={()=>void save('person')} page={editorPage} onPageChange={setEditorPage} message={error&&<p role="alert">{error}</p>} footer={<><button type="button" className="secondary-button" disabled={busy} onClick={()=>setEditor(undefined)}>Cancel</button><button className="microsoft-button" form="person-editor" type="submit" disabled={busy}>{busy?'Saving…':'Save person'}</button></>} pages={[
        {label:'Details',content:<><div className="dialog-field-grid"><label>Display name<input required maxLength={100} value={person.displayName} onChange={event=>setPerson({...person,displayName:event.target.value})}/></label><label>Person ID<input required maxLength={40} value={person.employeeCode} onChange={event=>setPerson({...person,employeeCode:event.target.value})}/></label></div><label className="access-check"><input type="checkbox" checked={person.active} onChange={event=>setPerson({...person,active:event.target.checked})}/>Active account</label></>},
        {label:'Assigned roles',content:<><table className="role-checkbox-table dialog-table"><thead><tr><th>Assign</th><th>Role</th><th>Permissions</th></tr></thead><tbody>{state.roles.slice(rolePage*5,rolePage*5+5).map(item=><tr key={item.id}><td><input type="checkbox" aria-label={'Assign '+item.name+' to '+(person.displayName||'new person')} checked={person.roleIds.includes(item.id)} onChange={event=>setPerson({...person,roleIds:event.target.checked?[...person.roleIds,item.id]:person.roleIds.filter(id=>id!==item.id)})}/></td><td>{item.name}</td><td>{item.permissions.length}</td></tr>)}</tbody></table><div className="compact-pagination"><span>Roles {rolePage*5+1}–{Math.min(rolePage*5+5,state.roles.length)} of {state.roles.length}</span><button type="button" className="secondary-button" disabled={rolePage===0} onClick={()=>setRolePage(value=>value-1)}>Previous</button><button type="button" className="secondary-button" disabled={(rolePage+1)*5>=state.roles.length} onClick={()=>setRolePage(value=>value+1)}>Next</button></div></>},
        {label:'Individual permissions',content:<><PermissionEditor individual label="Individual permission overrides" value={person.overrides} onChange={overrides=>setPerson({...person,overrides})} catalogue={state.catalogue}/></>}
      ]}/>}
      {tab==='assignments'&&<RoleAssignments people={state.people} roles={state.roles} departments={organization?.nodes.filter(node=>node.kind==='DEPARTMENT'&&node.active)??[]} membership={Object.fromEntries((organization?.assignments??[]).map(edge=>[edge.personId,edge.departmentId??organization?.nodes.find(node=>node.id===edge.teamId)?.parentId??undefined]))} department={department} onDepartmentChange={setDepartment} draft={assignmentDraft} setDraft={setAssignmentDraft} busy={busy} canManage={state.canManageUsers} onSave={()=>void saveAssignments()} message={error?<p role="alert">{error}</p>:notice?<p role="status">{notice}</p>:undefined} actionsContainer={pageActions}/>}
      {tab==='audit'&&<section className="profile-panel">{!state.audit.length?<p>No visible changes recorded.</p>:<div className="audit-scroll"><table><thead><tr><th>Time</th><th>Action</th><th>Actor</th><th>Target</th></tr></thead><tbody>{!visibleAudit.length&&<tr><td colSpan={4}>No matching changes.</td></tr>}{[...visibleAudit].reverse().map(item=><tr key={item.revision}><td>{new Date(item.at).toLocaleString()}</td><td className="audit-action">{actionLabel(item.action)}</td><td>{state.people.find(person=>person.id===item.actorId)?.displayName??item.actorId}</td><td>{state.roles.find(role=>role.id===item.targetId)?.name??state.people.find(person=>person.id===item.targetId)?.displayName??item.after?.name??item.targetId}</td></tr>)}</tbody></table></div>}</section>}
      </>}
    </main></div></div>;
}
