import {Link} from 'react-router';
import {ArrowUpRight,Layers,ShieldCheck,Clock3,FilePenLine,AlertCircle,Plus} from 'lucide-react';
import {SkillRadar,type TopReviewedSkill} from './SkillRadar';
export interface RecentCapabilityClaim {id:string;skillName:string;category:string;rank:number;levelName:string;status:'APPROVED'|'SUBMITTED'|'DRAFT'|'CHANGES_REQUESTED'|'REJECTED';updatedAt:string;href:string}
export interface DashboardCapabilityData {total:number;verified:number;pending:number;draft:number;changesRequested:number;rejected:number;canClaim:boolean;recentClaims:RecentCapabilityClaim[];topSkills?:TopReviewedSkill[]}
const labels={APPROVED:'Manager reviewed',SUBMITTED:'Pending review',DRAFT:'Self-assessed draft',CHANGES_REQUESTED:'Changes requested',REJECTED:'Not approved'};
export function DashboardCapability({data}:{data:DashboardCapabilityData}){
 const states=[{value:data.verified,status:'APPROVED',label:'Manager reviewed',tone:'teal',Icon:ShieldCheck},{value:data.pending,status:'SUBMITTED',label:'Pending review',tone:'amber',Icon:Clock3},{value:data.draft,status:'DRAFT',label:'Self-assessed drafts',tone:'blue',Icon:FilePenLine}];
 return <div className="dashboard-capability-body"><div className="dashboard-capability-total"><span><Layers size={17}/><strong>{data.total}</strong> {data.total===1?'skill claim':'skill claims'}</span>{data.canClaim&&<Link to="/my-skills?action=add"><Plus size={15}/>Add skill</Link>}</div>
 <div className="dashboard-capability-metrics">{states.map(({Icon,...s})=><Link key={s.status} className={'dashboard-metric '+s.tone} to={'/my-skills?status='+s.status}><Icon size={18}/><strong>{s.value}</strong><span>{s.label}</span></Link>)}</div>
 {data.topSkills?<SkillRadar skills={data.topSkills} reviewed={data.verified}/>:<p className="dashboard-footnote">Top-skill snapshot is unavailable. Your complete reviewed skills are available in My skills.</p>}
 {(data.changesRequested>0||data.rejected>0)&&<div className="dashboard-capability-followup">{data.changesRequested>0&&<Link to="/my-skills?status=CHANGES_REQUESTED"><AlertCircle size={16}/>{data.changesRequested} {data.changesRequested===1?'claim needs':'claims need'} changes<ArrowUpRight size={15}/></Link>}{data.rejected>0&&<Link to="/my-skills?status=REJECTED">{data.rejected} not approved · View feedback<ArrowUpRight size={15}/></Link>}</div>}
 {data.total===0?<div className="dashboard-empty"><ShieldCheck size={25}/><div><strong>Build your capability profile</strong><p>{data.canClaim?'Choose a published skill, describe your experience and prepare a claim for review.':'Your skill claims and their review status will appear here.'}</p>{data.canClaim&&<Link to="/my-skills?action=add">Add your first skill<ArrowUpRight size={15}/></Link>}</div></div>:data.recentClaims.length>0&&<section className="dashboard-capability-recent" aria-label="Recently updated skill claims"><h4>Recently updated</h4><ul>{data.recentClaims.map(c=><li key={c.id}><div><Link to={c.href} className="dashboard-claim-title">{c.skillName}<ArrowUpRight size={14}/></Link><p>{c.category} · Level {c.rank} — {c.levelName}</p><time dateTime={c.updatedAt}>Updated {new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(c.updatedAt))}</time></div><span className={'dashboard-claim-status '+c.status.toLowerCase()}>{labels[c.status]}</span></li>)}</ul></section>}
 <p className="dashboard-footnote">Reviewed proficiency and self-assessed claims are kept separate. Learning completion does not verify a skill.</p></div>;
}
