import {createPortal} from 'react-dom';
import {useEffect,useState} from 'react';
import {BookOpen,CalendarDays,Clock3,Flame,Plus,Check,ArrowLeft,ArrowRight} from 'lucide-react';
import {authenticatedFetch} from './auth';
import {FormDialog} from './FormDialog';
import './learning.css';
interface Task{id:string;title:string;plannedDate:string;estimatedMinutes:number;actualMinutes?:number;notes?:string;completedAt?:string}
interface Plan{id:string;revision:number;title:string;goal:string;timezone:string;dailyMinutes:number;targetDate:string;status:'ACTIVE'|'PAUSED'|'ARCHIVED';tasks:Task[]}
interface State{plans:Plan[];canManage:boolean}
import {dateInZone,shiftDay,currentStreak} from './learning-calendar';
async function read<T>(response:Response):Promise<T>{const body=await response.json().catch(()=>undefined);if(!response.ok)throw Error(body?.error?.message??'Learning could not be loaded. Try again.');return body;}
export function Learning({actionsContainer}:{actionsContainer?:HTMLElement|null}){
 const zone=Intl.DateTimeFormat().resolvedOptions().timeZone,today=dateInZone(new Date(),zone);
 const [state,setState]=useState<State>(),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[attempt,setAttempt]=useState(0);
 const [tab,setTab]=useState('Today'),[selectedDay,setSelectedDay]=useState(today),[month,setMonth]=useState(today.slice(0,7)),[creating,setCreating]=useState(false),[page,setPage]=useState(0),[reviewPage,setReviewPage]=useState(0);
 const [title,setTitle]=useState(''),[goal,setGoal]=useState(''),[minutes,setMinutes]=useState(30),[start,setStart]=useState(today),[taskText,setTaskText]=useState(''),[draftId,setDraftId]=useState(''),[taskIds,setTaskIds]=useState<string[]>([]);
 const [editing,setEditing]=useState<{plan:Plan;task:Task;action:'LOG'|'RESCHEDULE'}>(),[actual,setActual]=useState(30),[notes,setNotes]=useState(''),[newDay,setNewDay]=useState(today),[formError,setFormError]=useState(''),[archive,setArchive]=useState<Plan>();
 useEffect(()=>{const controller=new AbortController();authenticatedFetch('/api/learning',{signal:controller.signal}).then(read<State>).then(value=>{if(!controller.signal.aborted){setState(value);setError('');}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[attempt]);
 async function change(payload:object){if(busy)return false;setBusy(true);setFormError('');try{await read(await authenticatedFetch('/api/learning',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}));setAttempt(n=>n+1);setNotice('Learning updated.');return true;}catch(e){setFormError(e instanceof Error?e.message:'Could not save.');return false;}finally{setBusy(false);}}
 const plans=state?.plans??[],all=plans.flatMap(plan=>plan.tasks.map(task=>({plan,task}))),active=all.filter(x=>x.plan.status==='ACTIVE'),backlog=active.filter(x=>!x.task.completedAt&&x.task.plannedDate<dateInZone(new Date(),x.plan.timezone));
 const completed=all.filter(x=>x.task.completedAt),streak=currentStreak(completed.map(x=>dateInZone(new Date(x.task.completedAt!),zone)),today);
 const rows=(tab==='Backlog'?backlog:active.filter(x=>x.task.plannedDate===(tab==='Calendar'?selectedDay:dateInZone(new Date(),x.plan.timezone)))).sort((a,b)=>a.task.plannedDate.localeCompare(b.task.plannedDate));
 const names=taskText.split('\n').map(x=>x.trim()).filter(Boolean),target=shiftDay(start||today,Math.max(0,names.length-1));
 function openCreate(){setTitle('');setGoal('');setMinutes(30);setStart(today);setTaskText('');setDraftId(crypto.randomUUID());setTaskIds(Array.from({length:60},()=>crypto.randomUUID()));setPage(0);setReviewPage(0);setFormError('');setCreating(true);}
 function validate(){if(!title.trim()||title.trim().length>160||!goal.trim()||goal.length>2000||names.length<1||names.length>60||names.some(n=>n.length>160)||!Number.isInteger(minutes)||minutes<5||minutes>480||!/^20\d{2}-\d{2}-\d{2}$/.test(start)||!Number.isFinite(new Date(start+'T12:00:00Z').getTime())){setFormError('Enter a title, goal, valid start date, 5–480 minutes and 1–60 tasks (one per line).');return false;}setFormError('');return true;}
 const first=month+'-01',weekday=new Date(first+'T12:00:00Z').getUTCDay(),last=new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate();
 const newPlan=state?.canManage?<button className="admin-primary" onClick={openCreate}><Plus size={17}/>New plan</button>:null;
 return <div className="learning-page">
 {actionsContainer?createPortal(newPlan,actionsContainer):newPlan&&<div className="learning-toolbar">{newPlan}</div>}
 {error&&<p role="alert">{error} <button className="secondary-button" onClick={()=>setAttempt(n=>n+1)}>Retry</button></p>}{notice&&<p role="status">{notice}</p>}{!state&&!error&&<p role="status">Loading learning…</p>}
 {state&&<><div className="learning-metrics">{[{label:'Active plans',value:plans.filter(p=>p.status==='ACTIVE').length,icon:BookOpen},{label:'Completed tasks',value:completed.length,icon:Check},{label:'Minutes logged',value:completed.reduce((n,x)=>n+(x.task.actualMinutes??0),0),icon:Clock3},{label:'Current streak',value:streak+(streak===1?' day':' days'),icon:Flame}].map(({label,value,icon:Icon})=><section className="profile-panel" key={label}><Icon size={20}/><strong>{value}</strong><span>{label}</span></section>)}</div>
 <section className="profile-panel learning-workbench"><nav className="learning-tabs" aria-label="Learning views">{['Today','Calendar','Backlog','Plans'].map(name=><button key={name} className="secondary-button" aria-current={tab===name?'page':undefined} onClick={()=>setTab(name)}>{name}{name==='Backlog'&&backlog.length>0?' ('+backlog.length+')':''}</button>)}</nav>
 {tab==='Calendar'&&<div className="learning-calendar"><div className="panel-title"><button aria-label="Previous month" className="secondary-button" onClick={()=>setMonth(shiftDay(first,-1).slice(0,7))}><ArrowLeft size={16}/></button><h3>{new Date(first+'T12:00:00Z').toLocaleDateString(undefined,{month:'long',year:'numeric',timeZone:'UTC'})}</h3><button aria-label="Next month" className="secondary-button" onClick={()=>setMonth(shiftDay(first,32).slice(0,7))}><ArrowRight size={16}/></button></div><div className="calendar-grid">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day=><span key={day}>{day}</span>)}{Array.from({length:weekday},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:last},(_,i)=>{const day=month+'-'+String(i+1).padStart(2,'0'),count=active.filter(x=>x.task.plannedDate===day).length;return <button key={day} aria-label={day+(count?', '+count+(count===1?' task':' tasks'):'')} aria-pressed={selectedDay===day} onClick={()=>setSelectedDay(day)}><strong>{i+1}</strong>{count>0&&<small>{count} {count===1?'task':'tasks'}</small>}</button>;})}</div><h3>Tasks for {selectedDay}</h3></div>}
 {tab==='Plans'?<div className="learning-plans">{plans.length?plans.map(plan=>{const done=plan.tasks.filter(t=>t.completedAt).length;return <article key={plan.id}><div className="panel-title"><h3>{plan.title}</h3><span className="claim-status">{plan.status.toLowerCase()}</span></div><p>{plan.goal}</p><progress value={done} max={plan.tasks.length} aria-label={plan.title+' progress'}/><p className="workspace-muted">{done}/{plan.tasks.length} completed · {plan.dailyMinutes} min/day · Target {plan.targetDate}</p><small>{plan.timezone}</small>{state.canManage&&plan.status!=='ARCHIVED'&&<div className="learning-actions"><button disabled={busy} className="secondary-button" onClick={()=>void change({action:plan.status==='ACTIVE'?'PAUSE':'RESUME',id:plan.id,revision:plan.revision})}>{plan.status==='ACTIVE'?'Pause':'Resume'}</button><button disabled={busy} className="admin-text-button" onClick={()=>{setArchive(plan);setFormError('');}}>Archive</button></div>}</article>;}):<Empty label="Build a learning plan" detail="Choose a goal and break it into small daily tasks."/>}</div>:rows.length?<div className="learning-task-list">{rows.map(({plan,task})=><article key={task.id}><span className={'learning-task-icon '+(task.completedAt?'complete':'')}>{task.completedAt?<Check size={18}/>:<Clock3 size={18}/>}</span><div><h3>{task.title}</h3><p>{plan.title} · {task.plannedDate} · {task.completedAt?task.actualMinutes+' min logged':task.estimatedMinutes+' min planned'}</p>{task.notes&&<p>{task.notes}</p>}</div>{task.completedAt?<span className="claim-status">Completed</span>:state.canManage&&<div className="learning-actions"><button className="secondary-button" onClick={()=>{setEditing({plan,task,action:'RESCHEDULE'});setNewDay(today);setFormError('');}}>Reschedule</button><button className="admin-primary" onClick={()=>{setEditing({plan,task,action:'LOG'});setActual(task.estimatedMinutes);setNotes('');setFormError('');}}>Log completion</button></div>}</article>)}</div>:<Empty label={tab==='Backlog'?'No overdue tasks': 'No tasks scheduled'} detail={tab==='Backlog'?'Missed tasks stay here until you complete or reschedule them.':'Create a plan or choose another date to see your learning tasks.'}/>}
 {formError&&!creating&&!editing&&!archive&&<p role="alert">{formError}</p>}</section><p className="workspace-muted learning-footnote">Streaks count consecutive days with a completed task and at least one minute logged, in {zone}. Opening a task does not count. Learning progress does not verify a skill.</p></>}
 {creating&&<FormDialog title="New learning plan" busy={busy} onClose={()=>setCreating(false)} page={page} onPageChange={setPage} stepNavigation message={formError&&<p role="alert">{formError}</p>} pages={[{label:'Goal & time',content:<div className="access-form"><label>Plan name<input value={title} maxLength={160} onChange={e=>setTitle(e.target.value)} placeholder="Learn React fundamentals"/></label><label>Your goal<textarea rows={3} maxLength={2000} value={goal} onChange={e=>setGoal(e.target.value)} placeholder="What would you like to be able to do?"/></label><div className="learning-form-row"><label>Minutes per day<input type="number" min={5} max={480} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><label>Start date<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label></div><p className="workspace-muted">Timezone: {zone}. One task is scheduled each day.</p></div>},{label:'Daily tasks',content:<div className="access-form"><label>Tasks — one per line<textarea rows={7} value={taskText} maxLength={9660} onChange={e=>setTaskText(e.target.value)} placeholder={'Understand components\nPractice props and state\nBuild a small project'}/></label><p>{names.length} tasks · {minutes} minutes each · Finish {target}</p></div>},{label:'Review',content:<div><h3>{title||'Your learning plan'}</h3><p>{goal.length>300?goal.slice(0,300)+'… (full goal in Goal & time)':goal}</p><ol start={reviewPage*3+1}>{names.slice(reviewPage*3,reviewPage*3+3).map((name,i)=><li key={i}>{name} · {shiftDay(start,reviewPage*3+i)}</li>)}</ol>{names.length>3&&<div className="learning-actions"><button className="secondary-button" disabled={reviewPage===0} onClick={()=>setReviewPage(n=>n-1)}>Previous tasks</button><span>{reviewPage+1}/{Math.ceil(names.length/3)}</span><button className="secondary-button" disabled={(reviewPage+1)*3>=names.length} onClick={()=>setReviewPage(n=>n+1)}>More tasks</button></div>}<p>{names.length} daily tasks · {minutes} minutes/day · {start} to {target}</p><p className="workspace-muted">Tasks are saved to your personal workspace. Completion is logged separately when you do the work.</p></div>}]} footer={<><button className="secondary-button" disabled={busy} onClick={()=>page?setPage(page-1):setCreating(false)}>{page?'Back':'Cancel'}</button><button className="admin-primary" disabled={busy} onClick={()=>{if(page<2){if(page===1&&!validate())return;setPage(page+1);}else if(validate())void change({action:'CREATE',id:draftId,revision:0,title,goal,timezone:zone,dailyMinutes:minutes,targetDate:target,tasks:names.map((name,i)=>({id:taskIds[i],title:name,estimatedMinutes:minutes,plannedDate:shiftDay(start,i)}))}).then(ok=>{if(ok){setCreating(false);setTab('Plans');}});}}>{busy?'Saving…':page<2?'Next':'Create plan'}</button></>}/>}
 {editing&&<FormDialog title={editing.action==='LOG'?'Log completion':'Reschedule task'} busy={busy} onClose={()=>setEditing(undefined)} message={formError&&<p role="alert">{formError}</p>} footer={<><button className="secondary-button" disabled={busy} onClick={()=>setEditing(undefined)}>Cancel</button><button className="admin-primary" disabled={busy} onClick={()=>void change({action:editing.action,id:editing.plan.id,revision:editing.plan.revision,taskId:editing.task.id,...(editing.action==='LOG'?{actualMinutes:actual,notes}:{plannedDate:newDay})}).then(ok=>{if(ok)setEditing(undefined);})}>{busy?'Saving…':'Save'}</button></>}><div className="access-form"><h3>{editing.task.title}</h3>{editing.action==='LOG'?<><label>Actual minutes<input type="number" min={1} max={480} value={actual} onChange={e=>setActual(Number(e.target.value))}/></label><label>What did you learn? (optional)<textarea rows={3} maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label></>:<><label>New date<input type="date" max={editing.plan.targetDate} value={newDay} onChange={e=>setNewDay(e.target.value)}/></label><p>Daily capacity: {editing.plan.dailyMinutes} minutes. Target: {editing.plan.targetDate}. Tasks are moved only after you save.</p></>}</div></FormDialog>}
 {archive&&<FormDialog title="Archive learning plan" busy={busy} onClose={()=>setArchive(undefined)} message={formError&&<p role="alert">{formError}</p>} footer={<><button className="secondary-button" disabled={busy} onClick={()=>setArchive(undefined)}>Cancel</button><button className="admin-primary" disabled={busy} onClick={()=>void change({action:'ARCHIVE',id:archive.id,revision:archive.revision}).then(ok=>{if(ok)setArchive(undefined);})}>Archive plan</button></>}><p>Archive “{archive.title}”? Your logged progress is retained. Archived plans cannot be changed.</p></FormDialog>}
 </div>;
}
function Empty({label,detail}:{label:string;detail:string}){return <div className="learning-empty"><CalendarDays size={32}/><h3>{label}</h3><p>{detail}</p></div>;}
