import {useRef,useEffect,useState} from 'react';
import {BookOpen,CheckCircle2,Clock3,Target,Sparkles,ArrowRight,CalendarDays} from 'lucide-react';
import {FormDialog} from './FormDialog';
import {authenticatedFetch} from './auth';
import {AssistantRichText} from './AssistantRichText';
import {dateInZone} from './learning-calendar';
import type {Plan,Task} from './Learning';
import './learning-home.css';
interface Draft{kind:string;title:string;summary:string;body:string;steps:string[]}
interface Props{busy:boolean;plans:Plan[];canManage:boolean;tab:string;zone:string;onNew:()=>void;onPlanner:(goal:string)=>void;onRecover:(plan:Plan)=>void;onContinue:(plan:Plan,task:Task)=>void;onDraft:(draft:Draft)=>void;onStateChange:(plan:Plan)=>void;onArchive:(plan:Plan)=>void}
import {learningSummary,planWeeks} from './learning-progress';
const percent=(plan:Plan)=>plan.tasks.length?Math.round(plan.tasks.filter(t=>t.completedAt).length/plan.tasks.length*100):0;
export function LearningHome({busy,plans,canManage,tab,zone,onNew,onPlanner,onRecover,onContinue,onDraft,onStateChange,onArchive}:Props){
 const today=dateInZone(new Date(),zone),month=today.slice(0,7),summary=learningSummary(plans,month),active=plans.filter(p=>p.status==='ACTIVE');
 const pending=active.flatMap(plan=>plan.tasks.filter(task=>!task.completedAt).map(task=>({plan,task}))).sort((a,b)=>a.task.plannedDate.localeCompare(b.task.plannedDate)),current=pending[0];
 const recent=plans.flatMap(plan=>plan.tasks.filter(t=>t.completedAt).map(task=>({plan,task}))).sort((a,b)=>b.task.completedAt!.localeCompare(a.task.completedAt!));
 const [full,setFull]=useState<Plan>(),[weekIndex,setWeekIndex]=useState(0),[taskPage,setTaskPage]=useState(0),[queuePage,setQueuePage]=useState(0),[recentPage,setRecentPage]=useState(0),[allDeadlines,setAllDeadlines]=useState(false);
 const [ai,setAi]=useState<{reply:string;artifact?:Draft}>(),[aiBusy,setAiBusy]=useState(false),[aiError,setAiError]=useState(''),[aiMode,setAiMode]=useState('Recommendations'),[plannerGoal,setPlannerGoal]=useState('');const aiController=useRef<AbortController|null>(null);
 useEffect(()=>()=>aiController.current?.abort(),[]);
 async function generate(){
  if(aiBusy)return;const controller=new AbortController();aiController.current=controller;setAiBusy(true);setAiError('');setAiMode('Recommendations');
  const prompt='Use my_learning and my_skills to suggest up to 3 learning recommendations based on my current goals and available skill evidence. Identify the reason and next action for each. Distinguish an actual evidenced gap from a possible development opportunity. Do not invent skills, courses, providers, URLs, deadlines or proficiency improvement. If my goals are unclear, ask a focused question.';
  try{const response=await authenticatedFetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:prompt+(plannerGoal.trim()?' My learning goal: '+plannerGoal.trim():'')}),signal:controller.signal});const body=await response.json();if(!response.ok)throw Error(body?.error?.message??'Recommendations are unavailable.');if(!controller.signal.aborted)setAi({reply:body.reply,artifact:body.artifact});}catch(e){if(!controller.signal.aborted)setAiError(e instanceof Error?e.message:'Could not get recommendations.');}finally{if(!controller.signal.aborted)setAiBusy(false);}
 }
 useEffect(()=>{setQueuePage(p=>Math.min(p,Math.max(0,Math.ceil(pending.length/4)-1)));},[pending.length]);
 function viewPlan(plan:Plan){setFull(plan);setWeekIndex(0);setTaskPage(0);}
 const weeks=full?planWeeks(full):[],week=weeks[weekIndex];
 const goals=<section className="ld-card"><div className="ld-card-title"><h2>Learning goals</h2>{canManage&&<button className="admin-text-button" onClick={onNew}>Add goal <ArrowRight size={15}/></button>}</div>{plans.some(p=>p.status!=='ARCHIVED')?plans.filter(p=>p.status!=='ARCHIVED').map(plan=><button className="ld-goal" key={plan.id} onClick={()=>viewPlan(plan)}><span className="ld-icon"><Target size={19}/></span><span><strong>{plan.title}</strong><small>{plan.skillName??plan.focus??'General'} · {plan.status.toLowerCase()}</small><progress value={percent(plan)} max={100} aria-label={plan.title+' learning progress'}/></span><b>{percent(plan)}%</b></button>):<p className="workspace-muted">Add a goal to build your roadmap.</p>}</section>;
 const recommendations=<section className="ld-card ld-ai"><div className="ld-card-title"><h2><Sparkles size={18}/>Recommended for you</h2><span className="ld-ai-badge">AI {ai&&aiMode==='Recommendations'?'Recommended':'planner'}</span></div><p>Use your goals and available skill evidence to find your next learning opportunity.</p>{canManage&&<label className="ld-planner-goal">Your goal for the AI planner<input maxLength={300} value={plannerGoal} onChange={e=>setPlannerGoal(e.target.value)} placeholder="e.g. Build an Azure-backed API"/></label>}<div className="ld-ai-actions"><button className="secondary-button" disabled={aiBusy} onClick={()=>void generate()}>{aiBusy?'Preparing…':'Get recommendations'}</button>{canManage&&<button className="secondary-button" disabled={aiBusy} onClick={()=>onPlanner(plannerGoal)}>AI planner</button>}</div>{aiError&&<p role="alert">{aiError}</p>}{ai&&<div className="ld-ai-response"><h3>{aiMode}</h3><AssistantRichText>{ai.reply}</AssistantRichText>{canManage&&ai.artifact?.kind==='task_draft'&&ai.artifact.steps?.length>0&&<button className="admin-primary" onClick={()=>onDraft(ai.artifact!)}>Review plan draft <ArrowRight size={16}/></button>}<small>AI suggestions require your review. Nothing is saved until you create the plan.</small></div>}</section>;
 const paths=<section className="ld-card"><div className="ld-card-title"><h2>Personalized learning plans</h2>{canManage&&<button className="admin-text-button" onClick={onNew}>New plan</button>}</div>{plans.length?plans.map(plan=><article className="ld-path" key={plan.id}><div className="ld-card-title"><div><h3>{plan.title}</h3><p>{plan.skillName??plan.focus??'General'} · {plan.status.toLowerCase()}</p></div><b>{percent(plan)}%</b></div><progress value={percent(plan)} max={100} aria-label={plan.title+' completion'}/><p>{plan.tasks.filter(t=>t.completedAt).length}/{plan.tasks.length} tasks · {(plan.tasks.reduce((n,t)=>n+t.estimatedMinutes,0)/60).toFixed(1)} estimated hours · Target {plan.targetDate}</p><div className="ld-week-preview">{planWeeks(plan).slice(0,4).map(w=><span key={w.week}><strong>Week {w.week}</strong><small>{w.tasks.filter(t=>t.completedAt).length}/{w.tasks.length} done</small></span>)}</div><button className="secondary-button" onClick={()=>viewPlan(plan)}>View full plan <ArrowRight size={15}/></button>{canManage&&plan.status!=='ARCHIVED'&&<div className="learning-actions ld-plan-actions"><button className="admin-text-button" disabled={busy} onClick={()=>onStateChange(plan)}>{plan.status==='ACTIVE'?'Pause':'Resume'}</button>{plan.status==='ACTIVE'&&plan.tasks.some(t=>!t.completedAt&&t.plannedDate<dateInZone(new Date(),plan.timezone))&&<button className="admin-text-button" disabled={busy} onClick={()=>onRecover(plan)}>Recover plan</button>}<button className="admin-text-button" disabled={busy} onClick={()=>onArchive(plan)}>Archive</button></div>}</article>):<div className="ld-empty"><BookOpen size={28}/><h3>Start with a goal</h3><p>A small daily plan turns your goal into achievable steps.</p>{canManage&&<button className="admin-primary" onClick={onNew}>Create learning plan</button>}</div>}</section>;
 const queue=<section className="ld-card"><div className="ld-card-title"><h2>My learning queue</h2><span>{pending.length} pending</span></div>{pending.length?pending.slice(queuePage*4,queuePage*4+4).map(({plan,task})=><article className="ld-queue-row" key={task.id}><span className="ld-icon"><BookOpen size={20}/></span><div><h3>{task.title}</h3><p>{plan.skillName??plan.focus??'General'} · {task.estimatedMinutes} min · {task.plannedDate}</p><progress value={percent(plan)} max={100} aria-label={plan.title+' progress'}/></div><button className="secondary-button" onClick={()=>onContinue(plan,task)}>{percent(plan)?'Continue':'Start'}</button></article>):<p className="workspace-muted">No pending tasks. Your next plan will appear here.</p>}{pending.length>4&&<Pager page={queuePage} count={Math.ceil(pending.length/4)} change={setQueuePage}/>}</section>;
 return <>
 <div className="ld-summary">{[{label:'Active learning',value:active.length,icon:BookOpen},{label:'Monthly learning progress',value:summary.monthlyPercent+'%',icon:Target},{label:'Completed items',value:summary.completed,icon:CheckCircle2},{label:'AI recommendations',value:ai?'Ready':'On demand',icon:Sparkles,ai:true}].map(({label,value,icon:Icon,ai})=><section className={'ld-card '+(ai?'ld-ai-stat':'')} key={label}><Icon size={20}/><strong>{value}</strong><span>{label}</span></section>)}</div>
 {tab==='My learning'&&<><div className="ld-layout"><div className="ld-primary"><section className="ld-card"><div className="ld-card-title"><h2>Current focus</h2>{current&&<span className="claim-status">{current.plan.skillName??current.plan.focus??'General'}</span>}</div>{current?<div className="ld-focus"><div className="ld-focus-task"><span className="ld-icon"><BookOpen size={24}/></span><h3>{current.task.title}</h3><p>{current.plan.title}</p><div className="ld-progress-row"><progress value={percent(current.plan)} max={100} aria-label="Current plan progress"/><strong>{percent(current.plan)}%</strong></div><dl><div><dt><CalendarDays size={16}/>Scheduled</dt><dd>{current.task.plannedDate}</dd></div><div><dt><Clock3 size={16}/>Estimated time</dt><dd>{current.task.estimatedMinutes} minutes</dd></div></dl><div className="learning-actions"><button className="admin-primary" onClick={()=>onContinue(current.plan,current.task)}>Continue learning</button><button className="secondary-button" onClick={()=>viewPlan(current.plan)}>View full plan</button></div></div><div className="ld-focus-goal"><Target size={24}/><small>Learning goal</small><h3>{current.plan.title}</h3><p>{current.plan.goal.length>180?current.plan.goal.slice(0,180)+'…':current.plan.goal}</p><progress value={percent(current.plan)} max={100} aria-label="Goal learning progress"/><small>{current.plan.tasks.filter(t=>t.completedAt).length} of {current.plan.tasks.length} tasks completed</small><button className="secondary-button" onClick={()=>viewPlan(current.plan)}>View goal <ArrowRight size={15}/></button></div></div>:<div className="ld-empty"><Target size={28}/><h3>What would you like to learn?</h3><p>Create a goal to see your current focus and daily tasks.</p>{canManage&&<button className="admin-primary" onClick={onNew}>Add learning goal</button>}</div>}</section>{paths}{queue}{goals}<section className="ld-card"><div className="ld-card-title"><h2>Completed recently</h2><span>{recent.length} completed</span></div>{recent.length?recent.slice(recentPage*3,recentPage*3+3).map(({plan,task})=><article className="ld-queue-row" key={task.id}><span className="ld-icon ld-success"><CheckCircle2 size={20}/></span><div><h3>{task.title}</h3><p>{plan.skillName??plan.focus??'General'} · {task.actualMinutes} min · {dateInZone(new Date(task.completedAt!),plan.timezone)}</p></div><button className="admin-text-button" onClick={()=>onContinue(plan,task)}>View log</button></article>):<p className="workspace-muted">Completed tasks and your learning notes will appear here.</p>}{recent.length>3&&<Pager page={recentPage} count={Math.ceil(recent.length/3)} change={setRecentPage}/>}</section></div>
 <aside className="ld-secondary"><section className="ld-card"><h2>Learning progress</h2><div className="ld-month-progress"><div className="ld-ring" style={{background:`conic-gradient(var(--color-secondary) ${summary.monthlyPercent}%,var(--line) 0)`}}><span>{summary.monthlyPercent}%</span></div><div><strong>{new Date(today+'T12:00:00Z').toLocaleDateString(undefined,{month:'long',year:'numeric',timeZone:'UTC'})}</strong><p>{summary.monthlyDone} of {summary.monthlyTotal} scheduled items done</p><p>{(summary.loggedMinutes/60).toFixed(1)} hours logged · {(summary.plannedMinutes/60).toFixed(1)} hours planned</p></div></div></section><section className="ld-card"><div className="ld-card-title"><h2>Upcoming deadlines</h2>{pending.length>4&&<button className="admin-text-button" onClick={()=>setAllDeadlines(v=>!v)}>{allDeadlines?'Show less':'View all'}</button>}</div>{pending.slice(0,allDeadlines?pending.length:4).map(({plan,task})=><button className="ld-deadline" key={task.id} onClick={()=>onContinue(plan,task)}><span><CalendarDays size={18}/><b>{task.plannedDate.slice(8)}</b></span><span><strong>{task.title}</strong><small>{task.plannedDate} · {task.plannedDate<today?'Overdue':task.plannedDate===today?'Today':'Learning task'}</small></span></button>)}{!pending.length&&<p className="workspace-muted">No pending deadlines.</p>}</section>{recommendations}<section className="ld-card"><h2>Skill development</h2>{plans.filter(p=>p.skillId&&p.status!=='ARCHIVED').length?plans.filter(p=>p.skillId&&p.status!=='ARCHIVED').map(plan=><div className="ld-skill-progress" key={plan.id}><strong>{plan.skillName}</strong><progress value={percent(plan)} max={100} aria-label={plan.skillName+' learning completion'}/><small>{percent(plan)}% learning completion</small></div>):<p>Link a published skill when creating your next goal to track its learning progress here.</p>}<small>Learning completion is separate from assessed proficiency. Skill review determines your recorded level.</small></section></aside></div></>}
 {tab==='Learning paths'&&paths}{tab==='Goals'&&goals}{tab==='Recommendations'&&recommendations}
 {full&&week&&<FormDialog title={full.title} onClose={()=>setFull(undefined)} readOnly footer={<><button className="secondary-button" disabled={weekIndex===0} onClick={()=>{setWeekIndex(n=>n-1);setTaskPage(0);}}>Previous week</button><span>Week {week.week} · {week.tasks.filter(t=>t.completedAt).length}/{week.tasks.length} completed</span><button className="secondary-button" disabled={weekIndex+1>=weeks.length} onClick={()=>{setWeekIndex(n=>n+1);setTaskPage(0);}}>Next week</button></>}><div className="ld-plan-week"><div className="ld-week-heading"><label>Roadmap week<select value={weekIndex} onChange={e=>{setWeekIndex(Number(e.target.value));setTaskPage(0);}}>{weeks.map((w,i)=><option key={w.week} value={i}>Week {w.week} · {w.start}</option>)}</select></label><strong>{percent(full)}% complete</strong></div><p>{full.goal.length>240?full.goal.slice(0,240)+'…':full.goal}</p><p>{full.skillName??full.focus??'General'} · {(week.tasks.reduce((n,t)=>n+t.estimatedMinutes,0)/60).toFixed(1)} estimated hours</p>{week.tasks.slice(taskPage*3,taskPage*3+3).map(task=><article key={task.id} className={'ld-plan-task '+(current?.task.id===task.id?'is-current':'')}><div><strong>{task.title}</strong><small>{task.plannedDate} · {task.estimatedMinutes} min · {task.completedAt?'Completed':current?.task.id===task.id?'Current task':'Scheduled'}</small></div><button className="secondary-button" onClick={()=>{setFull(undefined);onContinue(full,task);}}>{task.completedAt?'View log':'Open task'}</button></article>)}{week.tasks.length>3&&<Pager page={taskPage} count={Math.ceil(week.tasks.length/3)} change={setTaskPage}/>}</div></FormDialog>}

 </>;
}
function Pager({page,count,change}:{page:number;count:number;change:(n:number)=>void}){return <div className="ld-pager"><button className="secondary-button" disabled={!page} onClick={()=>change(page-1)}>Previous</button><span>{page+1}/{count}</span><button className="secondary-button" disabled={page+1>=count} onClick={()=>change(page+1)}>Next</button></div>;}
