import {Link} from 'react-router';
import {Building2,ShieldCheck,UserRound,Compass,BookOpen,MessageSquare,Sparkles} from 'lucide-react';
import type {WorkspaceState} from './Workspace';
export interface Profile {id:string;displayName:string;employeeCode:string;organization:string;status:string;roles:string[]}
export function ProfileDetails({workspace,profile}:{workspace:WorkspaceState;profile?:Profile}){
 const person=profile??workspace.person,initials=person.displayName.trim().split(/\s+/).slice(0,2).map(part=>part[0]).join('');
 const demo=workspace.authentication==='local-demo';
 return <div className="personal-profile-page"><section className="profile-hero"><div className="profile-identity"><span className="profile-avatar" aria-hidden="true">{initials}</span><div><p className="profile-eyebrow">MY PROFILE</p><h2>{person.displayName}</h2><p>{person.employeeCode}</p></div></div><span className="profile-auth-badge"><ShieldCheck size={17}/>{demo?'Demo account':'Microsoft account'}</span></section>
 <div className="personal-profile-grid"><section className="profile-information"><header><UserRound size={20}/><h3>Work identity</h3></header><dl><div><dt>Full name</dt><dd>{person.displayName}</dd></div><div><dt>Employee ID</dt><dd>{person.employeeCode}</dd></div><div><dt>Workspace</dt><dd>{profile?.organization??'Loading workspace details…'}</dd></div><div><dt>Account status</dt><dd>{profile?.status==='ACTIVE'?'Active':profile?.status??'Checking…'}</dd></div></dl></section>
 <section className="profile-information"><header><ShieldCheck size={20}/><h3>Access & sign-in</h3></header><dl><div><dt>Sign-in method</dt><dd>{demo?'Temporary demo session':'Microsoft'}</dd></div><div><dt>Assigned roles</dt><dd className="profile-role-tags">{person.roles.length?person.roles.map(role=><span key={role}>{role}</span>):'No roles assigned'}</dd></div></dl><p>Available actions follow your effective permissions and scope.</p></section>
 <section className="profile-information profile-destinations"><header><Building2 size={20}/><h3>Your workspace</h3></header>{workspace.capabilities.ownSkills&&<Link to="/my-skills"><Compass size={20}/><div><strong>My skills</strong><span>Experience, evidence and review status</span></div></Link>}{workspace.capabilities.learning&&<Link to="/learning"><BookOpen size={20}/><div><strong>Learn & Grow</strong><span>Goals, daily tasks and progress</span></div></Link>}{workspace.capabilities.requests&&<Link to="/requests?action=create"><MessageSquare size={20}/><div><strong>Request a profile correction</strong><span>Send an update to the right person</span></div></Link>}</section>
 <section className="profile-information"><header><Sparkles size={20}/><h3>Need guidance?</h3></header><p>Get help understanding your profile, available actions or the next step in your development.</p><button className="secondary-button" onClick={()=>window.dispatchEvent(new CustomEvent('assistant-context-request',{detail:{prompt:'Help me understand my own profile and available actions. Use my current effective permissions; ask what I want to update before preparing any draft.'}}))}>Ask AI assistant</button></section></div></div>;
}
