import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';
import {useSearchParams} from 'react-router';
import {RefreshCw,Plus,MessageSquare,ArrowLeft,CheckCircle2,XCircle,Send} from 'lucide-react';
import {authenticatedFetch} from './auth';
import {RequestActionDialog,type RequestAction} from './RequestActionDialog';
import {RequestList} from './RequestList';
import {RequestComposer} from './RequestComposer';
import {requestRead,categoryLabel,requestStatusLabel,type RequestOptions,type RequestRecord} from './request-model';
import './requests.css';
interface Detail{record:RequestRecord;events:{id:string;action:string;body:string;actorName:string;at:string;revision:number}[]}
const when=(s:string)=>new Date(s).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});
export function Requests({actionsContainer}:{actionsContainer?:HTMLElement|null}){
 const [params,setParams]=useSearchParams(),selected=params.get('record');
 const [options,setOptions]=useState<RequestOptions>(),[detail,setDetail]=useState<Detail>(),[attempt,setAttempt]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[creating,setCreating]=useState(false);
 const [operation,setOperation]=useState<RequestAction>(),[timelinePage,setTimelinePage]=useState(0);
 useEffect(()=>{if(params.get('action')!=='create'||!options)return;const next=new URLSearchParams(params);next.delete('action');setParams(next,{replace:true});if(options.canRequest||options.canIncident)setCreating(true);else setError('Your current permissions do not allow creating a request.');},[params,options]);
 useEffect(()=>{const update=()=>setAttempt(n=>n+1);window.addEventListener('requests-updated',update);return()=>window.removeEventListener('requests-updated',update);},[]);
 useEffect(()=>{const c=new AbortController();authenticatedFetch('/api/workflows/options',{signal:c.signal}).then(requestRead<RequestOptions>).then(o=>{if(!c.signal.aborted)setOptions(o);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[attempt]);
 useEffect(()=>{setError('');setDetail(undefined);setTimelinePage(0);if(!selected)return;const c=new AbortController();authenticatedFetch('/api/workflows/'+encodeURIComponent(selected),{signal:c.signal}).then(requestRead<Detail>).then(d=>{if(!c.signal.aborted)setDetail(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[attempt,selected]);
 function saved(message:string){setNotice(message);setAttempt(n=>n+1);window.dispatchEvent(new Event('notifications-updated'));}

 const action=options&&(options.canRequest||options.canIncident)?<button className="admin-primary" onClick={()=>{setNotice('');setCreating(true);}}><Plus size={17}/>New request</button>:null,current=detail?.record;
 return <div className="requests-page">
 {actionsContainer?createPortal(action,actionsContainer):action}
 {notice&&<p className="request-notice" role="status"><CheckCircle2 size={18}/>{notice}<button aria-label="Dismiss request notification" className="admin-text-button" onClick={()=>setNotice('')}>Dismiss</button></p>}
 {error&&<p role="alert">{error} <button className="secondary-button" onClick={()=>setAttempt(n=>n+1)}>Retry</button></p>}
 <RequestList active={!selected} refresh={attempt} onOpen={id=>{setNotice('');setParams({record:id});}}/>
 {selected&&<><button className="admin-text-button request-back" onClick={()=>{setNotice('');setParams({});}}><ArrowLeft size={17}/>Back to requests</button>{!detail&&!error&&<div className="notification-destination-loading" role="status"><RefreshCw size={26} className="notification-spin"/><strong>Opening request…</strong><p>Loading the latest activity and your available actions.</p></div>}{current&&<div className="request-detail-grid"><section className="profile-panel"><div className="panel-title"><span className="request-kind">{current.reference} · {current.kind==='REQUEST'?'Request':'Incident'}</span><span className={'request-status '+current.status.toLowerCase()}>{requestStatusLabel(current.status)}</span></div><h2>{current.title}</h2><span className="request-topic">{categoryLabel(current.category)}</span><p className="request-description">{current.description}</p><dl className="request-meta"><div><dt>Requested by</dt><dd>{current.requesterName}</dd></div><div><dt>Recipient</dt><dd>{current.recipientName}</dd></div><div><dt>Priority</dt><dd>{current.priority==='HIGH'?'High':'Normal'}</dd></div><div><dt>Created</dt><dd>{when(current.createdAt)}</dd></div></dl><div className="request-actions">{current.canStart&&<button className="admin-primary" onClick={()=>setOperation('START')}>Start work</button>}{current.canResolve&&<button className="admin-primary" onClick={()=>setOperation('RESOLVE')}>Resolve</button>}{current.canReassign&&<button className="secondary-button" onClick={()=>setOperation('REASSIGN')}>Reassign</button>}{current.canComment&&<button className="secondary-button" onClick={()=>setOperation('COMMENT')}><MessageSquare size={17}/>Add comment</button>}{current.canCancel&&<button className="admin-text-button" onClick={()=>setOperation('CANCEL')}><XCircle size={17}/>{current.kind==='INCIDENT'?'Cancel incident':'Cancel request'}</button>}</div></section>
 <section className="profile-panel request-timeline"><h2>Activity</h2><ol>{detail!.events.slice().reverse().slice(timelinePage*4,timelinePage*4+4).map(e=><li key={e.id}>{e.action==='CANCEL'?<XCircle size={18}/>:e.action==='COMMENT'?<MessageSquare size={18}/>:<CheckCircle2 size={18}/>}<div><strong>{({CREATE:'Submitted',CANCEL:'Cancelled',START:'Work started',RESOLVE:'Resolved',REASSIGN:'Reassigned',COMMENT:'Comment'} as Record<string,string>)[e.action]??e.action}</strong><small>{e.actorName} · {when(e.at)}</small><p>{e.body}</p></div></li>)}</ol>{detail!.events.length>4&&<div className="request-pagination"><button className="secondary-button" disabled={timelinePage===0} onClick={()=>setTimelinePage(p=>p-1)}>Newer</button><span>{timelinePage+1}/{Math.ceil(detail!.events.length/4)}</span><button className="secondary-button" disabled={(timelinePage+1)*4>=detail!.events.length} onClick={()=>setTimelinePage(p=>p+1)}>Older</button></div>}</section></div>}</>}
 {creating&&options&&<RequestComposer options={options} onClose={()=>setCreating(false)} onSaved={id=>{setCreating(false);setParams({record:id});saved('Submitted. Your recipient has been notified.');}}/>}
 {operation&&current&&<RequestActionDialog record={current} action={operation} onClose={()=>setOperation(undefined)} onReload={()=>{setOperation(undefined);setAttempt(n=>n+1);}} onSaved={()=>{setOperation(undefined);if(operation==='REASSIGN')setParams({});saved(({COMMENT:'Comment posted.',CANCEL:'Cancelled. History retained.',START:'Work started.',RESOLVE:'Resolved. The requester has been notified.',REASSIGN:'Reassigned. The new recipient has been notified.'})[operation]);}}/>}
 </div>;
}
