import {useEffect,useState} from 'react';
import {useSearchParams} from 'react-router';
import {authenticatedFetch} from './auth';
import {FormDialog} from './FormDialog';
import type {Claim} from './MySkills';
import {TeamCapability} from './TeamCapability';
import {ReviewHistory} from './ReviewHistory';
import {ReviewAssistance} from './ReviewAssistance';
import {ClaimReviewAccess,type ClaimReviewDecision} from './ClaimReviewAccess';
import './review-workbench.css';

async function result<T>(response:Response):Promise<T>{const data=await response.json().catch(()=>undefined);if(!response.ok)throw Error(data?.error?.message??'This action could not finish. Reload to check the current state before retrying.');return data;}
export function SkillClaimDialog({claim,mode,onClose,onSaved,history=false}:{history?:boolean;claim:Claim;mode:'view'|'submit'|'review';onClose:()=>void;onSaved:()=>void}){
 const [page,setPage]=useState(0),[feedback,setFeedback]=useState(''),[decision,setDecision]=useState('REQUEST_CHANGES'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function apply(){if(busy||(mode==='review'&&!claim.reviewAccess?.allowed))return;setBusy(true);setError('');try{await result(await authenticatedFetch(mode==='submit'?'/api/my-skills/submit':'/api/skill-reviews/decision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:claim.id,revision:claim.revision,action:mode==='submit'?'SUBMIT':decision,feedback})}));onSaved();}catch(reason){setError(reason instanceof Error?reason.message:'Could not complete this review.');}finally{setBusy(false);}}
 const textPages=(label:string,text:string)=>((text||'None provided.').match(/[\s\S]{1,650}/g)??[]).map((part,index)=>({label:label+(index?' (continued)':''),content:<><h3>{label}</h3><p className="claim-level-description">{part}</p></>}));
 const pages=[
  {label:'Claim summary',content:<><h3>{claim.personName??claim.skillName}</h3>{history&&<ClaimReviewAccess decision={claim.reviewAccess}/>}<dl className="profile-details"><div><dt>Skill</dt><dd>{claim.skillName}</dd></div><div><dt>Proficiency</dt><dd>{claim.levelName} Â· Level {claim.rank}</dd></div><div><dt>Experience</dt><dd>{claim.experienceMonths} months</dd></div><div><dt>Status</dt><dd>{claim.status.replaceAll('_',' ')}</dd></div></dl></>},
  ...textPages('Experience',claim.description),...textPages('Level criteria',claim.levelDescription??''),...textPages('Projects',claim.projects??''),...textPages('Evidence references',claim.evidence??''),
  ...(history?[{label:'AI assistance',content:<ReviewAssistance claim={claim} canDraft={mode==='review'} decision={decision} onDecision={setDecision} onUse={setFeedback} hasFeedback={Boolean(feedback.trim())}/>},{label:'History',content:<ReviewHistory id={claim.id}/>}]:[]),
  {label:mode==='review'?'Decision':'Review',content:mode==='review'?<><label>Decision<select value={decision} disabled={busy} onChange={event=>setDecision(event.target.value)}><option value="REQUEST_CHANGES">Request changes</option><option value="APPROVE">Approve</option><option value="REJECT">Reject</option></select></label><label>Feedback<textarea rows={5} required maxLength={2000} value={feedback} disabled={busy} onChange={event=>setFeedback(event.target.value)}/></label><p>Approval records a manager-reviewed proficiency claim, separate from learning quizzes and certifications.</p></>:<><h3>{mode==='submit'?'Confirm submission':'Review status'}</h3>{mode==='submit'&&<p>Your current reporting manager will receive this submission. Submitted claims cannot be edited until changes are requested or the claim is rejected. If your manager changed, resubmitting routes the pending claim to the current manager.</p>}</>},
  ...(mode!=='review'?textPages('Manager feedback',claim.feedback??'No review feedback yet.'):[]),
 ];
 return <FormDialog title={mode==='review'?'Review skill claim':mode==='submit'?'Submit skill claim':claim.skillName} busy={busy} onClose={onClose} page={page} onPageChange={setPage} message={error&&<p role="alert">{error}</p>}
 pages={pages} footer={<><button className="secondary-button" disabled={busy} onClick={onClose}>{mode==='view'?'Close':'Cancel'}</button>{page<pages.length-1?<button className="admin-primary" disabled={busy} onClick={()=>setPage(value=>value+1)}>Continue</button>:mode!=='view'&&<button className="admin-primary" disabled={busy||(mode==='review'&&(!feedback.trim()||!claim.reviewAccess?.allowed))} onClick={()=>void apply()}>{busy?'Savingâ€¦':mode==='submit'?'Submit for review':'Confirm decision'}</button>}</>}/>;
}
interface ReviewQueue {claims:Claim[];total:number;pageSize:number;canViewTeam?:boolean;canReadHistory?:boolean;categories?:string[];summary?:{pending:number;approved:number;changes:number;rejected:number}}
const reviewLabels:Record<string,string>={SUBMITTED:'Pending review',APPROVED:'Manager reviewed',CHANGES_REQUESTED:'Changes requested',REJECTED:'Not approved',ALL:'All review states'};
export function SkillReviews(){
 const [params,setParams]=useSearchParams(),[view,setView]=useState<'queue'|'team'>('queue');
 const [data,setData]=useState<ReviewQueue>(),[page,setPage]=useState(1),[attempt,setAttempt]=useState(0),[loading,setLoading]=useState(true),[opening,setOpening]=useState(false),[error,setError]=useState(''),[claim,setClaim]=useState<Claim>(),[notice,setNotice]=useState('');
 const [search,setSearch]=useState(''),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[status,setStatus]=useState('SUBMITTED'),[person,setPerson]=useState<string>();
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setClaim(undefined);const filters=new URLSearchParams({page:String(page),search:query,category,status});if(person)filters.set('person',person);authenticatedFetch('/api/skill-reviews?'+filters,{signal:controller.signal}).then(result<ReviewQueue>).then(value=>{if(!controller.signal.aborted)setData(value);}).catch(reason=>{if(!controller.signal.aborted){setData(undefined);setClaim(undefined);setError(reason.message);}}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[page,attempt,query,category,status,person]);
 useEffect(()=>{const id=params.get('claim');if(!id||loading||!data)return;const next=new URLSearchParams(params);next.delete('claim');setParams(next,{replace:true});void openClaim(id);},[params,loading,data]);
 async function openClaim(id:string){if(opening)return;setOpening(true);setError('');try{if(!data?.canReadHistory){const item=data?.claims.find(c=>c.id===id);if(!item)throw Error('This claim is unavailable in your current queue.');setClaim(item);}else{const detail=await result<{claim:Claim;reviewAccess:ClaimReviewDecision}>(await authenticatedFetch('/api/skill-reviews/'+encodeURIComponent(id)));setClaim({...detail.claim,reviewAccess:detail.reviewAccess});}}catch(e){setClaim(undefined);setError(e instanceof Error?e.message:'Review unavailable.');}finally{setOpening(false);}}
 function clear(){setSearch('');setQuery('');setCategory('');setStatus('SUBMITTED');setPerson(undefined);setPage(1);}
 return <><nav className="review-workspace-tabs" aria-label="Skill review workspace"><button className="secondary-button" aria-pressed={view==='queue'} onClick={()=>setView('queue')}>Review queue</button>{data?.canViewTeam&&<button className="secondary-button" aria-pressed={view==='team'} onClick={()=>setView('team')}>Team capability</button>}</nav>{view==='team'&&data?.canViewTeam?<TeamCapability onReviews={id=>{setPerson(id);setStatus('SUBMITTED');setPage(1);setQuery('');setSearch('');setView('queue');}}/>:<>
 {notice&&<p role="status" className="access-message">{notice}</p>}{error&&<p role="alert">{error}<button className="secondary-button" onClick={()=>setAttempt(n=>n+1)}>Retry</button></p>}
 <section className="review-workbench" aria-label="Assigned skill reviews"><header><div><h2>Skill reviews</h2><p>Current direct reports Â· Claims assigned to you</p></div><button className="secondary-button" disabled={loading} onClick={()=>setAttempt(n=>n+1)}>Refresh</button></header>
 {data?.summary&&<div className="review-metrics" aria-label="Filter reviews by status">{[{key:'SUBMITTED',label:'Pending review',value:data.summary.pending},{key:'APPROVED',label:'Manager reviewed',value:data.summary.approved},{key:'CHANGES_REQUESTED',label:'Changes requested',value:data.summary.changes},{key:'REJECTED',label:'Not approved',value:data.summary.rejected}].map(s=><button key={s.key} disabled={loading} aria-pressed={status===s.key} onClick={()=>{setStatus(s.key);setPage(1);}}><strong>{s.value}</strong><span>{s.label}</span></button>)}</div>}
 <form className="review-filters" onSubmit={e=>{e.preventDefault();setPage(1);setQuery(search.trim());}}><input type="search" aria-label="Search review employee or skill" placeholder="Search employee, code or skillâ€¦" maxLength={100} value={search} onChange={e=>setSearch(e.target.value)}/><button className="secondary-button">Search</button><label><span>Category</span><select aria-label="Review category" value={category} onChange={e=>{setCategory(e.target.value);setPage(1);}}><option value="">All categories</option>{data?.categories?.map(c=><option key={c}>{c}</option>)}</select></label><label><span>Status</span><select aria-label="Review status" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}>{Object.entries(reviewLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button type="button" className="secondary-button" onClick={clear}>Clear</button></form>
 {loading&&<p role="status">Loading scoped reviewsâ€¦</p>}{opening&&<p role="status">Checking current claim accessâ€¦</p>}
 {!loading&&data&&!data.claims.length&&<div className="directory-empty"><h3>{status==='SUBMITTED'&&!query&&!category?'No pending reviews':'No matching reviews'}</h3><p>{status==='SUBMITTED'?'New submissions from your assigned direct reports will appear here.':'Try another filter or search. Private drafts are excluded.'}</p></div>}
 {!loading&&data&&data.claims.length>0&&<div className="my-skills-table-wrap"><table className="my-skills-table"><thead><tr><th>Employee</th><th>Skill / category</th><th>Claimed proficiency</th><th>Status</th><th>Updated</th><th>Action</th></tr></thead><tbody>{data.claims.map(item=><tr key={item.id}><td><strong>{item.personName}</strong></td><td><strong>{item.skillName}</strong><span className="review-subtext">{item.category}</span></td><td>Level {item.rank}<span className="review-subtext">{item.levelName}</span></td><td><span className={'team-status '+(item.status==='APPROVED'?'reviewed':'pending')}>{reviewLabels[item.status]??item.status}</span></td><td>{new Date(item.updatedAt).toLocaleDateString()}</td><td><button className="secondary-button" disabled={opening} onClick={()=>void openClaim(item.id)}>{item.status==='SUBMITTED'?'Review':'View & history'}</button></td></tr>)}</tbody></table></div>}
 <footer><span>{data?.total??'â€¦'} matching claims Â· Page {page}</span><button className="secondary-button" disabled={loading||page===1} onClick={()=>setPage(n=>n-1)}>Previous</button><button className="secondary-button" disabled={loading||!data||page*data.pageSize>=data.total} onClick={()=>setPage(n=>n+1)}>Next</button></footer></section>
 {claim&&<SkillClaimDialog claim={claim} mode={claim.status==='SUBMITTED'&&claim.reviewAccess?.allowed?'review':'view'} history={data?.canReadHistory} onClose={()=>setClaim(undefined)} onSaved={()=>{setClaim(undefined);setNotice('Review saved. The employee has been notified.');setAttempt(n=>n+1);window.dispatchEvent(new Event('notifications-updated'));}}/>}</>}</>;
}
