import {useEffect,useState} from 'react';
import {authenticatedFetch} from './auth';
import {FormDialog} from './FormDialog';
import type {Claim} from './MySkills';

async function result<T>(response:Response):Promise<T>{const data=await response.json().catch(()=>undefined);if(!response.ok)throw Error(data?.error?.message??'This action could not finish. Reload to check the current state before retrying.');return data;}
export function SkillClaimDialog({claim,mode,onClose,onSaved}:{claim:Claim;mode:'view'|'submit'|'review';onClose:()=>void;onSaved:()=>void}){
 const [page,setPage]=useState(0),[feedback,setFeedback]=useState(''),[decision,setDecision]=useState('REQUEST_CHANGES'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function apply(){if(busy)return;setBusy(true);setError('');try{await result(await authenticatedFetch(mode==='submit'?'/api/my-skills/submit':'/api/skill-reviews/decision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:claim.id,revision:claim.revision,action:mode==='submit'?'SUBMIT':decision,feedback})}));onSaved();}catch(reason){setError(reason instanceof Error?reason.message:'Could not complete this review.');}finally{setBusy(false);}}
 const textPages=(label:string,text:string)=>((text||'None provided.').match(/[\s\S]{1,650}/g)??[]).map((part,index)=>({label:label+(index?' (continued)':''),content:<><h3>{label}</h3><p className="claim-level-description">{part}</p></>}));
 const pages=[
  {label:'Claim summary',content:<><h3>{claim.personName??claim.skillName}</h3><dl className="profile-details"><div><dt>Skill</dt><dd>{claim.skillName}</dd></div><div><dt>Proficiency</dt><dd>{claim.levelName} · Level {claim.rank}</dd></div><div><dt>Experience</dt><dd>{claim.experienceMonths} months</dd></div><div><dt>Status</dt><dd>{claim.status.replaceAll('_',' ')}</dd></div></dl></>},
  ...textPages('Experience',claim.description),...textPages('Level criteria',claim.levelDescription??''),...textPages('Projects',claim.projects??''),...textPages('Evidence references',claim.evidence??''),
  {label:mode==='review'?'Decision':'Review',content:mode==='review'?<><label>Decision<select value={decision} disabled={busy} onChange={event=>setDecision(event.target.value)}><option value="REQUEST_CHANGES">Request changes</option><option value="APPROVE">Approve</option><option value="REJECT">Reject</option></select></label><label>Feedback<textarea rows={5} required maxLength={2000} value={feedback} disabled={busy} onChange={event=>setFeedback(event.target.value)}/></label><p>Approval records a manager-reviewed proficiency claim, separate from learning quizzes and certifications.</p></>:<><h3>{mode==='submit'?'Confirm submission':'Review status'}</h3>{mode==='submit'&&<p>Your current reporting manager will receive this submission. Submitted claims cannot be edited until changes are requested or the claim is rejected. If your manager changed, resubmitting routes the pending claim to the current manager.</p>}</>},
  ...(mode!=='review'?textPages('Manager feedback',claim.feedback??'No review feedback yet.'):[]),
 ];
 return <FormDialog title={mode==='review'?'Review skill claim':mode==='submit'?'Submit skill claim':claim.skillName} busy={busy} onClose={onClose} page={page} onPageChange={setPage} message={error&&<p role="alert">{error}</p>}
 pages={pages} footer={<><button className="secondary-button" disabled={busy} onClick={onClose}>{mode==='view'?'Close':'Cancel'}</button>{page<pages.length-1?<button className="admin-primary" disabled={busy} onClick={()=>setPage(value=>value+1)}>Continue</button>:mode!=='view'&&<button className="admin-primary" disabled={busy||(mode==='review'&&!feedback.trim())} onClick={()=>void apply()}>{busy?'Saving…':mode==='submit'?'Submit for review':'Confirm decision'}</button>}</>}/>;
}
export function SkillReviews(){
 const [data,setData]=useState<{claims:Claim[];total:number;pageSize:number}>(),[page,setPage]=useState(1),[attempt,setAttempt]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[claim,setClaim]=useState<Claim>(),[notice,setNotice]=useState('');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');authenticatedFetch(`/api/skill-reviews?page=${page}`,{signal:controller.signal}).then(result<{claims:Claim[];total:number;pageSize:number}>).then(value=>{if(!controller.signal.aborted)setData(value);}).catch(reason=>{if(!controller.signal.aborted)setError(reason.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[page,attempt]);
 return <>{notice&&<p role="status" className="access-message">{notice}</p>}{error&&<p role="alert">{error}<button className="secondary-button" onClick={()=>setAttempt(value=>value+1)}>Retry</button></p>}<section className="profile-panel" aria-label="Assigned skill reviews"><div className="panel-title"><h2>Review queue {data?.total??''}</h2><button className="secondary-button" disabled={loading} onClick={()=>setAttempt(value=>value+1)}>Refresh</button></div><p>Submitted claims assigned to you from your current direct reports.</p>{loading&&<p role="status">Loading assigned reviews…</p>}{!loading&&data&&!data.claims.length&&<p>No claims awaiting your review.</p>}{data&&data.claims.length>0&&<div className="my-skills-table-wrap"><table className="my-skills-table"><thead><tr><th>Employee</th><th>Skill</th><th>Proficiency</th><th>Action</th></tr></thead><tbody>{data.claims.map(item=><tr key={item.id}><td>{item.personName}</td><td>{item.skillName}</td><td>{item.levelName}</td><td><button className="secondary-button" disabled={loading} onClick={()=>setClaim(item)}>Review</button></td></tr>)}</tbody></table></div>}<div className="catalogue-pagination"><span>Page {page}</span><button className="secondary-button" disabled={loading||page===1} onClick={()=>setPage(value=>value-1)}>Previous</button><button className="secondary-button" disabled={loading||!data||page*data.pageSize>=data.total} onClick={()=>setPage(value=>value+1)}>Next</button></div></section>{claim&&<SkillClaimDialog claim={claim} mode="review" onClose={()=>setClaim(undefined)} onSaved={()=>{setClaim(undefined);setNotice('Review saved. The employee has been notified.');setAttempt(value=>value+1);}}/>}</>;
}
