import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowUpRight,Search,UsersRound} from 'lucide-react';
import {authenticatedFetch} from './auth';
import './team-capability.css';
interface Person {id:string;name:string;employeeCode:string;reviewed:number;pending:number}
interface Team {total:number;pageSize:number;people:Person[];skills:{personId:string;skillName:string;category:string;rank:number;levelName:string;status:'APPROVED'|'SUBMITTED'}[]}
export function TeamCapability({onReviews}:{onReviews:(personId:string)=>void}){
 const [data,setData]=useState<Team>(),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(1),[person,setPerson]=useState<string>(),[attempt,setAttempt]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();setLoading(true);setData(undefined);setError('');const params=new URLSearchParams({page:String(page),search:query});if(person)params.set('person',person);
 authenticatedFetch('/api/skill-reviews/team?'+params,{signal:c.signal}).then(async response=>{const body=await response.json().catch(()=>undefined);if(!response.ok)throw Error(body?.error?.message??'Team capability could not be loaded.');return body as Team;}).then(value=>{if(!c.signal.aborted)setData(value);}).catch(reason=>{if(!c.signal.aborted)setError(reason.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[query,page,person,attempt]);
 const selected=person?data?.people[0]:undefined;
 return <section className="team-capability" aria-label="Direct report capability">
 <header><span className="team-symbol"><UsersRound size={22}/></span><div><h2>{selected?.name??'Your direct reports'}</h2><p>Current reporting assignments · Reviewed skills and assigned pending claims</p></div><button className="secondary-button" disabled={loading} onClick={()=>setAttempt(n=>n+1)}>Refresh</button></header>
 {person?<button className="dashboard-link team-back" onClick={()=>{setPerson(undefined);setPage(1);setQuery('');setSearch('');}}><ArrowLeft size={16}/>All direct reports</button>:<form className="team-search" onSubmit={event=>{event.preventDefault();setPage(1);setQuery(search.trim());}}><Search size={19}/><input aria-label="Search direct reports" placeholder="Search name or employee code" maxLength={100} value={search} onChange={e=>setSearch(e.target.value)}/><button className="secondary-button" disabled={loading}>Search</button>{query&&<button type="button" className="secondary-button" onClick={()=>{setQuery('');setSearch('');setPage(1);}}>Clear</button>}</form>}
 {loading&&<p role="status">Resolving your current team access…</p>}
 {error&&<div role="alert"><p>{error}</p><button className="secondary-button" onClick={()=>setAttempt(n=>n+1)}>Retry</button></div>}
 {!loading&&data&&!person&&<><p className="team-result-count">{data.total} accessible direct {data.total===1?'report':'reports'}{query?' matching your search':''}</p>{!data.people.length?<div className="directory-empty"><h3>{query?'No matching direct reports':'No active direct reports'}</h3><p>{query?'Try another name or employee code.':'Reporting assignments determine this list. Organization permission does not expose other reporting branches here.'}</p></div>:<div className="team-people">{data.people.map(p=><button key={p.id} className="team-person" onClick={()=>{setPerson(p.id);setPage(1);setQuery('');}}><div><span className="team-avatar">{p.name.split(' ').map(s=>s[0]).slice(0,2).join('')}</span><div><strong>{p.name}</strong><span>{p.employeeCode}</span></div><ArrowUpRight size={18}/></div><dl><div><dt>Manager reviewed</dt><dd>{p.reviewed}</dd></div><div><dt>Awaiting your review</dt><dd>{p.pending}</dd></div></dl><span className="team-open">View skills →</span></button>)}</div>}<footer><span>Page {page}</span><button className="secondary-button" disabled={page===1} onClick={()=>setPage(n=>n-1)}>Previous</button><button className="secondary-button" disabled={page*data.pageSize>=data.total} onClick={()=>setPage(n=>n+1)}>Next</button></footer></>}
 {!loading&&data&&selected&&<><div className="team-member-summary"><span>{selected.employeeCode}</span><strong>{selected.reviewed} manager reviewed</strong><strong>{selected.pending} awaiting your review</strong>{selected.pending>0&&<button className="secondary-button" onClick={()=>onReviews(selected.id)}>Open review queue</button>}</div>{!data.skills.length?<div className="directory-empty"><h3>No reviewed or assigned pending skills</h3><p>Private drafts and other reviewers’ pending claims are excluded.</p></div>:<div className="my-skills-table-wrap"><table className="my-skills-table"><thead><tr><th>Skill</th><th>Category</th><th>Proficiency</th><th>Status</th></tr></thead><tbody>{data.skills.map((s,i)=><tr key={i}><td><strong>{s.skillName}</strong></td><td>{s.category}</td><td>Level {s.rank} · {s.levelName}</td><td><span className={'team-status '+(s.status==='APPROVED'?'reviewed':'pending')}>{s.status==='APPROVED'?'Manager reviewed':'Awaiting your review'}</span></td></tr>)}</tbody></table></div>}<p className="team-note">Learning completion is separate from reviewed proficiency. Private draft details remain with the employee.</p></>}
 </section>;
}
