export const permissionCatalogue = [
  ['profile.view', 'View profiles'],
  ['profile.edit', 'Edit profile fields'],
  ['skill.view', 'View published skills'],
  ['skill.claim', 'Submit skill and certification claims'],
  ['skill.verify', 'Review assigned skill and certification claims'],
  ['skill.catalogue.propose', 'Propose master amendments'],
  ['skill.catalogue.manage', 'Manage skill catalogue'],
  ['evidence.view', 'View evidence'],
  ['evidence.submit', 'Submit evidence'],
  ['assessment.view', 'View assessments'],
  ['assessment.approve', 'Approve assigned assessments'],
  ['learning.recommend', 'Recommend learning to current direct reports'],
  ['learning.view', 'View learning plans'],
  ['learning.manage', 'Manage learning plans'],
  ['learning.approve', 'Approve learning proposals'],
  ['demand.view', 'View demand'],
  ['demand.create', 'Create demand'],
  ['demand.approve', 'Approve demand'],
  ['matching.view', 'View matches'],
  ['matching.run', 'Run matching'],
  ['matching.shortlist', 'Shortlist candidates'],
  ['reports.view', 'View reports'],
  ['reports.export', 'Export reports'],
  ['users.view', 'View users'],
  ['users.manage', 'Manage users'],
  ['permissions.manage', 'Manage roles and individual permissions'],
  ['audit.view', 'View audit history'],
  ['request.create', 'Create requests'],
  ['request.view', 'View requests'],
  ['request.assign', 'Assign requests'],
  ['request.approve', 'Approve master amendments'],
  ['request.resolve', 'Resolve requests'],
  ['incident.create', 'Report incidents'],
  ['incident.view', 'View incidents'],
  ['incident.assign', 'Assign incidents'],
  ['incident.resolve', 'Resolve incidents'],
] as const;
export type PermissionCode = (typeof permissionCatalogue)[number][0];
