import sql from 'mssql';
import {withRuntimeDatabase} from '../../shared/database.js';
import {AccessError} from '../../shared/errors.js';
import {learningChange,type LearningPlan,type LearningChange,type LearningStore} from './learning.js';
export class SqlLearningStore implements LearningStore {
 constructor(private accountId:string){}
 async read(actor:string){try{return await withRuntimeDatabase(async pool=>{const result=await pool.request().input('account_id',sql.UniqueIdentifier,this.accountId).input('actor_id',sql.UniqueIdentifier,actor).execute('dbo.ReadOwnLearningPlans');const sets=result.recordsets as unknown as [sql.IRecordSet<{canManage:boolean}>,sql.IRecordSet<{id:string;revision:number;status:LearningPlan['status'];payload:string}>];return {canManage:sets[0][0].canManage,plans:sets[1].map(row=>{const data=JSON.parse(row.payload);return {id:row.id.toLowerCase(),revision:row.revision,status:row.status,title:data.title,goal:data.goal,timezone:data.timezone,dailyMinutes:data.dailyMinutes,targetDate:data.targetDate,focus:data.focus??'General',skillId:data.skillId,skillName:data.skillName,tasks:data.tasks} as LearningPlan;})};});}catch(error){throw learningError(error);}}
 async change(actor:string,input:LearningChange){const change=learningChange(input);try{await withRuntimeDatabase(pool=>pool.request().input('account_id',sql.UniqueIdentifier,this.accountId).input('actor_id',sql.UniqueIdentifier,actor).input('plan_id',sql.UniqueIdentifier,change.id).input('expected_revision',sql.Int,change.revision).input('action',sql.VarChar(20),change.action).input('payload',sql.NVarChar(sql.MAX),JSON.stringify(change)).execute('dbo.ChangeOwnLearningPlan'));}catch(error){throw learningError(error);}}
}
function learningError(error:unknown){const number=(error as {number?:number})?.number;if(number===51003)return new AccessError(403,'Your current permissions do not allow this learning action.');if(number===51004)return new AccessError(404,'This learning plan or task is unavailable.');if(number===51009||number===2601||number===2627)return new AccessError(409,'The plan changed or was already saved. Reload before continuing.');if(number===51000||number===51010)return new AccessError(400,'Check the task, date, daily capacity and current plan status.');return error;}
