import sql from 'mssql';
import {withRuntimeDatabase} from '../../shared/database.js';
import {AccessError} from '../../shared/errors.js';
import type {PracticeStore,PracticeState} from './practice.js';
export class SqlPracticeStore implements PracticeStore {
 constructor(private accountId:string){}
 private async run(actor:string,plan:string,task:string,action:string,payload:object){try{return await withRuntimeDatabase(pool=>pool.request().input('account_id',sql.UniqueIdentifier,this.accountId).input('actor_id',sql.UniqueIdentifier,actor).input('plan_id',sql.UniqueIdentifier,plan).input('task_id',sql.UniqueIdentifier,task).input('action',sql.VarChar(20),action).input('payload',sql.NVarChar(sql.MAX),JSON.stringify(payload)).execute('dbo.OwnLearningPractice'));}catch(e){const number=(e as {number?:number}).number;if(number===51003)throw new AccessError(403,'Your current permissions do not allow this learning action.');if(number===51004)throw new AccessError(404,'This task or quiz is unavailable.');if(number===51009||number===2601||number===2627)throw new AccessError(409,'The session changed. Reload it before saving again.');if(number===51000||number===51010)throw new AccessError(400,'Check your answers, session fields, practice limit and plan status.');throw e;}}
 async read(actor:string,plan:string,task:string):Promise<PracticeState>{const result=await this.run(actor,plan,task,'READ',{}),sets=result.recordsets as sql.IRecordSet<Record<string,unknown>>[];const s=sets[0][0];return {session:s?{...JSON.parse(String(s.payload)),revision:Number(s.revision)}:{revision:0,notes:'',minutes:0,resources:[]},quizzes:sets[1].map(q=>({id:String(q.id).toLowerCase(),title:String(q.title),provider:String(q.provider),createdAt:new Date(String(q.createdAt)).toISOString(),questions:JSON.parse(String(q.questions))})),attempts:sets[2].map(a=>({id:String(a.id).toLowerCase(),quizId:String(a.quizId).toLowerCase(),answers:JSON.parse(String(a.answers)),score:Number(a.score),total:Number(a.total),submittedAt:new Date(String(a.submittedAt)).toISOString()}))};}
 async write(actor:string,plan:string,task:string,action:'SESSION'|'QUIZ'|'ATTEMPT',payload:object){await this.run(actor,plan,task,action,payload);}
}
