import type { CertificationRecord } from './types';

export const INITIAL_CERTIFICATIONS: CertificationRecord[] = [
  {
    srNo: 26,
    id: 'cert-26',
    name: 'Anupriya Banerjee',
    employeeCode: '704427',
    du: 'DU UK (IN001)',
    category: 'OCI Infra',
    certificationName: 'Oracle Cloud Infrastructure Digital Assistant Professional',
    certificationDate: '2023-09-20',
    doesNotExpire: 'Yes',
    expiryDate: '2050-12-31',
    active: 'Y',
    emailId: 'anupriya.banerjee@soprasteria.com',
    emailType: 'Sopra',
    provider: 'Oracle',
    credentialId: 'OCI-DA-704427-23',
    credentialUrl: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=OCI-DA-704427',
    status: 'APPROVED',
    verified: true,
    reviewedBy: 'Capability Reviewer',
    reviewedAt: '2023-09-22',
  },
  {
    srNo: 27,
    id: 'cert-27',
    name: 'Anupriya Banerjee',
    employeeCode: '704427',
    du: 'DU UK (IN001)',
    category: 'Oracle AI',
    certificationName: 'Oracle Cloud Infrastructure Generative AI Certified Professional',
    certificationDate: '2024-06-27',
    doesNotExpire: 'No',
    expiryDate: '2026-06-27',
    active: 'N',
    emailId: 'anupriya.banerjee@soprasteria.com',
    emailType: 'Sopra',
    provider: 'Oracle',
    credentialId: 'OCI-GAI-704427-24',
    credentialUrl: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=OCI-GAI-704427',
    status: 'CHANGES_REQUESTED',
    feedbackNote: 'Please update with the latest renewed badge link as validity verification is pending.',
    verified: false,
    reviewedBy: 'Capability Reviewer',
    reviewedAt: '2024-07-02',
  },
  {
    srNo: 28,
    id: 'cert-28',
    name: 'Anupriya Banerjee',
    employeeCode: '704427',
    du: 'DU UK (IN001)',
    category: 'HR & Payroll',
    certificationName: 'Oracle Fusion Cloud Applications HCM Certified Foundations Associate',
    certificationDate: '2025-05-19',
    doesNotExpire: 'Yes',
    expiryDate: '2050-12-31',
    active: 'Y',
    emailId: 'anupriya.banerjee@soprasteria.com',
    emailType: 'Sopra',
    provider: 'Oracle',
    credentialId: 'OF-HCM-704427-25',
    credentialUrl: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=OF-HCM-704427',
    status: 'APPROVED',
    verified: true,
    reviewedBy: 'Capability Reviewer',
    reviewedAt: '2025-05-25',
  },
  {
    srNo: 29,
    id: 'cert-29',
    name: 'Anupriya Banerjee',
    employeeCode: '704427',
    du: 'DU UK (IN001)',
    category: 'HR & Payroll',
    certificationName: 'Oracle HCM Business Process Certified Foundations Associate Rel 2',
    certificationDate: '2023-10-11',
    doesNotExpire: 'Yes',
    expiryDate: '2050-12-31',
    active: 'Y',
    emailId: 'anupriya.banerjee@soprasteria.com',
    emailType: 'Sopra',
    provider: 'Oracle',
    credentialId: 'OF-BP-704427-23',
    credentialUrl: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=OF-BP-704427',
    status: 'APPROVED',
    verified: true,
    reviewedBy: 'Capability Reviewer',
    reviewedAt: '2023-10-15',
  },
  {
    srNo: 30,
    id: 'cert-30',
    name: 'Anupriya Banerjee',
    employeeCode: '704427',
    du: 'DU UK (IN001)',
    category: 'HR & Payroll',
    certificationName: 'Oracle Global Human Resources Cloud 2023 Certified Implementation Professional',
    certificationDate: '2023-11-22',
    doesNotExpire: 'No',
    expiryDate: '2025-05-22',
    active: 'N',
    emailId: 'anupriya.banerjee@soprasteria.com',
    emailType: 'Sopra',
    provider: 'Oracle',
    credentialId: 'OF-GHR-704427-23',
    credentialUrl: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=OF-GHR-704427',
    status: 'APPROVED',
    verified: true,
    reviewedBy: 'Capability Reviewer',
    reviewedAt: '2023-11-28',
  },
  {
    srNo: 31,
    id: 'cert-31',
    name: 'Anupriya Banerjee',
    employeeCode: '704427',
    du: 'DU UK (IN001)',
    category: 'HR & Payroll',
    certificationName: 'Oracle Global Human Resources Cloud 2025 Certified Implementation Professional',
    certificationDate: '2025-08-08',
    doesNotExpire: 'No',
    expiryDate: '2027-01-24',
    active: 'Y',
    emailId: 'anupriya.banerjee@soprasteria.com',
    emailType: 'Sopra',
    provider: 'Oracle',
    credentialId: 'OF-GHR-704427-25',
    credentialUrl: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=OF-GHR-704427',
    status: 'APPROVED',
    verified: true,
    reviewedBy: 'Capability Reviewer',
    reviewedAt: '2025-08-12',
  },
  {
    srNo: 32,
    id: 'cert-32',
    name: 'Anupriya Banerjee',
    employeeCode: '704427',
    du: 'DU UK (IN001)',
    category: 'HR & Payroll',
    certificationName: 'Oracle Payroll Cloud 2022 Certified Implementation Professional',
    certificationDate: '2023-04-04',
    doesNotExpire: 'No',
    expiryDate: '2024-10-04',
    active: 'N',
    emailId: 'anupriya.banerjee@soprasteria.com',
    emailType: 'Sopra',
    provider: 'Oracle',
    credentialId: 'OF-PAY-704427-22',
    credentialUrl: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=OF-PAY-704427',
    status: 'APPROVED',
    verified: true,
    reviewedBy: 'Capability Reviewer',
    reviewedAt: '2023-04-10',
  },
  {
    srNo: 321,
    id: 'cert-321',
    name: 'Anupriya Banerjee',
    employeeCode: '704427',
    du: 'DU UK (IN001)',
    category: 'HR & Payroll',
    certificationName: 'Oracle Payroll Cloud 2026 Certified Implementation Professional',
    certificationDate: '2026-08-09',
    doesNotExpire: 'No',
    expiryDate: '2028-09-02',
    active: 'Y',
    emailId: 'anupriya.banerjee@soprasteria.com',
    emailType: 'Sopra',
    provider: 'Oracle',
    credentialId: 'OF-PAY-704427-26',
    credentialUrl: 'https://catalog-education.oracle.com/pls/certview/sharebadge?id=OF-PAY-704427-26',
    status: 'APPROVED',
    verified: true,
    reviewedBy: 'Capability Reviewer',
    reviewedAt: '2026-08-14',
  },
  // Active pending verification submissions to demonstrate the skill review workflow
  {
    srNo: 322,
    id: 'cert-322',
    name: 'Rahul Sharma',
    employeeCode: '709182',
    du: 'DU UK (IN001)',
    category: 'Cloud Architecture',
    certificationName: 'AWS Certified Solutions Architect – Associate',
    certificationDate: '2026-09-15',
    doesNotExpire: 'No',
    expiryDate: '2029-09-15',
    active: 'Y',
    emailId: 'rahul.sharma@soprasteria.com',
    emailType: 'Sopra',
    provider: 'Amazon Web Services',
    credentialId: 'AWS-SAA-709182',
    credentialUrl: 'https://www.credly.com/badges/aws-saa-709182',
    status: 'SUBMITTED',
    verified: false,
    submittedAt: '2026-09-16',
  },
  {
    srNo: 323,
    id: 'cert-323',
    name: 'Priya Nair',
    employeeCode: '705331',
    du: 'DU UK (IN001)',
    category: 'DevOps & SRE',
    certificationName: 'Microsoft Certified: Azure DevOps Engineer Expert',
    certificationDate: '2026-09-28',
    doesNotExpire: 'No',
    expiryDate: '2027-09-28',
    active: 'Y',
    emailId: 'priya.nair@soprasteria.com',
    emailType: 'Sopra',
    provider: 'Microsoft',
    credentialId: 'MS-AZ400-705331',
    credentialUrl: 'https://learn.microsoft.com/users/priyanair/transcript/cert-az400',
    status: 'SUBMITTED',
    verified: false,
    submittedAt: '2026-09-29',
  },
  {
    srNo: 324,
    id: 'cert-324',
    name: 'Khushi Agarwal',
    employeeCode: 'DEMO-NHS-002',
    du: 'DU UK (IN001)',
    category: 'Cloud Architecture',
    certificationName: 'Microsoft Certified: Azure Fundamentals (AZ-900)',
    certificationDate: '2024-02-14',
    doesNotExpire: 'Yes',
    expiryDate: '2050-12-31',
    active: 'Y',
    emailId: 'khushi.agarwal@soprasteria.com',
    emailType: 'Sopra',
    provider: 'Microsoft',
    credentialId: 'MS-AZ900-002',
    credentialUrl: 'https://learn.microsoft.com/transcript/cert-az900-khushi',
    status: 'APPROVED',
    verified: true,
    reviewedBy: 'Capability Reviewer',
    reviewedAt: '2024-02-18',
  },
  {
    srNo: 325,
    id: 'cert-325',
    name: 'Khushi Agarwal',
    employeeCode: 'DEMO-NHS-002',
    du: 'DU UK (IN001)',
    category: 'Cloud Architecture',
    certificationName: 'AWS Certified Cloud Practitioner',
    certificationDate: '2026-08-10',
    doesNotExpire: 'No',
    expiryDate: '2029-08-10',
    active: 'Y',
    emailId: 'khushi.agarwal@soprasteria.com',
    emailType: 'Sopra',
    provider: 'Amazon Web Services',
    credentialId: 'AWS-CCP-002',
    credentialUrl: 'https://www.credly.com/badges/aws-ccp-khushi',
    status: 'SUBMITTED',
    verified: false,
    submittedAt: '2026-08-11',
  },
];

const STORAGE_KEY = 'cil.certifications.v1';

export function loadStoredCertifications(): CertificationRecord[] {
  if (typeof window === 'undefined') return INITIAL_CERTIFICATIONS;
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return INITIAL_CERTIFICATIONS;
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) && parsed.length > 0 ? parsed : INITIAL_CERTIFICATIONS;
  } catch {
    return INITIAL_CERTIFICATIONS;
  }
}

export function saveStoredCertifications(items: CertificationRecord[]): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(items));
    window.dispatchEvent(new Event('certifications-updated'));
  } catch {
    // quota exceeded or disabled
  }
}
